/*
 * Copyright (C) 2010 John D Lamb
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or (at
 * your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

#ifndef CCGSL_MATRIX_UCHAR_HPP
#define CCGSL_MATRIX_UCHAR_HPP

#include<gsl/gsl_matrix.h>
#include<new>

#include"exception.hpp"
#include"vector_uchar.hpp"

// This file is autogenerated

namespace gsl {
  /**
   * This class handles matrix_uchar objects as shared handles. It models a random access container
   * so that STL functions work with matrix_uchar.
   *
   * Note that matrix_uchar_views are implemented as matrix_uchar objects here.
   */
  class matrix_uchar {
  public:
    /**
     * The default constructor is only really useful for assigning to.
     */
    matrix_uchar(){
      ccgsl_pointer = 0;
      // just plausibly we could fail to allocate count
      try { count = new size_t; } catch( std::bad_alloc& e ){
	throw e;
      }
      *count = 1; // initially there is just one reference to ccgsl_pointer
    }
    // Refines random access container
    // Refines assignable
    /**
     * The default constructor creates a new matrix_uchar with n elements
     * @param n1 The number of rows in the matrix_uchar
     * @param n2 The number of columns in the matrix_uchar
     */
    explicit matrix_uchar( size_t const n1, size_t const n2 ){
      ccgsl_pointer = gsl_matrix_uchar_alloc( n1, n2 );
      // just plausibly we could allocate matrix_uchar but not count
      try { count = new size_t; } catch( std::bad_alloc& e ){
	// try to tidy up before rethrowing
	gsl_matrix_uchar_free( ccgsl_pointer );
	throw e;
      }
      *count = 1; // initially there is just one reference to ccgsl_pointer
    }
    /**
     * Could construct from a gsl_matrix_uchar. This is not usually a good idea. In this case
     * we should not use gsl_matrix_uchar_free() to deallocate the memory.
     * @param v The matrix_uchar
     */
    explicit matrix_uchar( gsl_matrix_uchar* v ){
      ccgsl_pointer = v;
      // just plausibly we could fail to allocate count: no further action needed.
      count = new size_t;
      *count = 1; // initially there is just one reference to ccgsl_pointer
    }
    // copy constructor
    /**
     * The copy constructor. This shares the matrix_uchar. Use clone() if you want a full copy.
     * @param v The matrix_uchar to copy.
     */
    matrix_uchar( matrix_uchar const& v ) : ccgsl_pointer( v.ccgsl_pointer ), count( v.count ){
      ++*count; // matrix_uchar is now shared.
    }
    // assignment operator
    /**
     * The assignment operator. This makes a shared copy.
     * @param v The matrix_uchar to copy
     */
    matrix_uchar& operator=( matrix_uchar const& v ){
      // first, possibly delete anything pointed to by this
      if( --*count == 0 ){
	if( ccgsl_pointer != 0 ) gsl_matrix_uchar_free( ccgsl_pointer );
	delete count;
      }
      // Then copy
      ccgsl_pointer = v.ccgsl_pointer;
      count = v.count;
      ++*count; // block_uchar is now shared.
      return *this;
    }
    // clone()
    /**
     * The clone function. Use this if you want a copy of the block_uchar that does
     * not share the underlying data.
     * @return a new copy of this.
     */
    matrix_uchar clone() const {
      matrix_uchar copy( get()->size1, get()->size2 );
      // Now copy
      gsl_matrix_uchar_memcpy( copy.get(), get() );
      // return new object
      return copy;
    }
    // destructor
    /**
     * The destructor only deletes the pointers if count reaches zero.
     */
    ~matrix_uchar(){
      if( --*count == 0 ){
	// could have allocated null pointer
	if( ccgsl_pointer != 0 ) gsl_matrix_uchar_free( ccgsl_pointer );
	delete count;
      }
    }
    // Sizes
    /**
     * The number of rows of the matrix_uchar
     * @return The number of rows of the matrix_uchar
     */
    size_t size1() const { return ccgsl_pointer == 0 ? 0 : ccgsl_pointer->size1; }
    /**
     * The number of columns of the matrix_uchar
     * @return The number of columns of the matrix_uchar
     */
    size_t size2() const { return ccgsl_pointer == 0 ? 0 : ccgsl_pointer->size2; }
    /**
     * Swap two matrix_uchar objects. This works even if the matrix_uchar objects have different sizes
     * because it swaps pointers.
     * @param m The matrix_uchar to swap with @c this.
     */
    void swap( matrix_uchar& m ){
      gsl_matrix_uchar* tmp = ccgsl_pointer; ccgsl_pointer = m.ccgsl_pointer; m.ccgsl_pointer = tmp;
      size_t* tmp2 = count; count = m.count; m.count = tmp2;
    }
    // view operations
    /**
     * C++ version of gsl_matrix_uchar_submatrix().
     * @param i Index in @c this of first row of submatrix
     * @param j Index in @c this of first column of submatrix
     * @param n1 Number of rows of submatrix
     * @param n2 Number of columns of submatrix
     * @return The submatrix
     */
    matrix_uchar submatrix( size_t const i, size_t const j, size_t const n1, size_t const n2 ){
      gsl_matrix_uchar* m = static_cast<gsl_matrix_uchar*>( malloc( sizeof( gsl_matrix_uchar ) ) );
      *m = gsl_matrix_uchar_submatrix( get(), i, j, n1, n2 ).matrix;
      return matrix_uchar( m );
    }
    /**
     * C++ version of gsl_matrix_uchar_row().
     * @param i A row index
     * @return A row as a vector_uchar
     */
    vector_uchar row( size_t const i ){
      gsl_vector_uchar* w = static_cast<gsl_vector_uchar*>( malloc( sizeof( gsl_vector_uchar ) ) );
      *w = gsl_matrix_uchar_row( get(), i ).vector;
      return vector_uchar( w );
    }
    /**
     * C++ version of gsl_matrix_uchar_column().
     * @param j A column index
     * @return A column as a vector_uchar
     */
    vector_uchar column( size_t const j ){
      gsl_vector_uchar* w = static_cast<gsl_vector_uchar*>( malloc( sizeof( gsl_vector_uchar ) ) );
      *w = gsl_matrix_uchar_column( get(), j ).vector;
      return vector_uchar( w );
    }
    /**
     * C++ version of gsl_matrix_uchar_diagonal().
     * @return The principal diagonal as a vector_uchar
     */
    vector_uchar
    diagonal(){ gsl_vector_uchar* w = static_cast<gsl_vector_uchar*>( malloc( sizeof( gsl_vector_uchar ) ) );
      *w = gsl_matrix_uchar_diagonal( get() ).vector;
      return vector_uchar( w );
    }
    /**
     * C++ version of gsl_matrix_uchar_subdiagonal().
     * @param k An index
     * @return Subdiagonal @c k as a vector_uchar
     */
    vector_uchar subdiagonal( size_t const k ){
      gsl_vector_uchar* w = static_cast<gsl_vector_uchar*>( malloc( sizeof( gsl_vector_uchar ) ) );
      *w = gsl_matrix_uchar_subdiagonal( get(), k ).vector;
      return vector_uchar( w );
    }
    /**
     * C++ version of gsl_matrix_uchar_superdiagonal().
     * @param k An index
     * @return Subdiagonal @c k as a vector_uchar
     */
    vector_uchar superdiagonal( size_t const k ){
      gsl_vector_uchar* w = static_cast<gsl_vector_uchar*>( malloc( sizeof( gsl_vector_uchar ) ) );
      *w = gsl_matrix_uchar_superdiagonal( get(), k ).vector;
      return vector_uchar( w );
    }
    /**
     * C++ version of gsl_matrix_uchar_subrow().
     * @param i A row index
     * @param offset A column offset
     * @param n The number of elements
     * @return A subrow as a vector_uchar
     */
    vector_uchar subrow( size_t const i, size_t const offset, size_t const n ){
      gsl_vector_uchar* w = static_cast<gsl_vector_uchar*>( malloc( sizeof( gsl_vector_uchar ) ) );
      *w = gsl_matrix_uchar_subrow( get(), i, offset, n ).vector;
      return vector_uchar( w );
    }
    /**
     * C++ version of gsl_matrix_uchar_subcolumn().
     * @param j A column index
     * @param offset A row offset
     * @param n The number of elements
     * @return A subcolumn as a vector_uchar
     */
    vector_uchar subcolumn( size_t const j, size_t const offset, size_t const n ){
      gsl_vector_uchar* w = static_cast<gsl_vector_uchar*>( malloc( sizeof( gsl_vector_uchar ) ) );
      *w = gsl_matrix_uchar_subcolumn( get(), j, offset, n ).vector;
      return vector_uchar( w );
    }
   /**
     * C++ version of gsl_matrix_uchar_view_array().
     * @param base An array of type unsigned char
     * @param n1 The number of rows
     * @param n2 The number of columns
     * @return A matrix_uchar
     */
    static matrix_uchar view_array( unsigned char* base, size_t const n1, size_t const n2 ){
      gsl_matrix_uchar* m = static_cast<gsl_matrix_uchar*>( malloc( sizeof( gsl_matrix_uchar ) ) );
      *m = gsl_matrix_uchar_view_array( base, n1, n2 ).matrix;
      return matrix_uchar( m );
    }
    /**
     * C++ version of gsl_matrix_uchar_view_array_with_tda().
     * @param base An array of type unsigned char
     * @param n1 The number of rows
     * @param n2 The number of columns
     * @param tda The number of columns in memory
     * @return A matrix_uchar
     */
    static matrix_uchar view_array_with_tda( unsigned char* base, size_t const n1, size_t const n2, size_t const tda ){
      gsl_matrix_uchar* m = static_cast<gsl_matrix_uchar*>( malloc( sizeof( gsl_matrix_uchar ) ) );
      *m =  gsl_matrix_uchar_view_array_with_tda( base, n1, n2, tda ).matrix;
      return matrix_uchar( m );
    }
    /**
     * C++ version of gsl_matrix_uchar_view_vector().
     * @param v A vector_uchar
     * @param n1 The number of rows
     * @param n2 The number of columns
     * @return A matrix_uchar
     */
    static matrix_uchar view_vector( vector_uchar& v, size_t const n1, size_t const n2 ){
      gsl_matrix_uchar* m = static_cast<gsl_matrix_uchar*>( malloc( sizeof( gsl_matrix_uchar ) ) );
      *m =  gsl_matrix_uchar_view_vector( v.get(), n1, n2 ).matrix;
      return matrix_uchar( m );
    }
    /**
     * C++ version of gsl_matrix_uchar_view_vector_with_tda().
     * @param v A vector_uchar
     * @param n1 The number of rows
     * @param n2 The number of columns
     * @param tda The number of columns in memory
     * @return A matrix_uchar
     */
    static matrix_uchar view_vector_with_tda( vector_uchar& v, size_t const n1, size_t const n2, size_t const tda ){
      gsl_matrix_uchar* m = static_cast<gsl_matrix_uchar*>( malloc( sizeof( gsl_matrix_uchar ) ) );
      *m = gsl_matrix_uchar_view_vector_with_tda( v.get(), n1, n2, tda ).matrix;
      return matrix_uchar( m );
    }
    // const versions ...
    /**
     * C++ version of gsl_matrix_uchar_const_submatrix().
     * @param i Index in @c this of first row of submatrix
     * @param j Index in @c this of first column of submatrix
     * @param n1 Number of rows of submatrix
     * @param n2 Number of columns of submatrix
     * @return The submatrix
     */
    matrix_uchar const const_submatrix( size_t const i, size_t const j, size_t const n1, size_t const n2 ) const {
      gsl_matrix_uchar* m = static_cast<gsl_matrix_uchar*>( malloc( sizeof( gsl_matrix_uchar ) ) );
      *m = gsl_matrix_uchar_const_submatrix( get(), i, j, n1, n2 ).matrix;
      return matrix_uchar( m );
    }
    /**
     * C++ version of gsl_matrix_uchar_const_row().
     * @param i A row index
     * @return A row as a vector_uchar
     */
    vector_uchar const const_row( size_t const i ) const {
      gsl_vector_uchar* w = static_cast<gsl_vector_uchar*>( malloc( sizeof( gsl_vector_uchar ) ) );
      *w = gsl_matrix_uchar_const_row( get(), i ).vector;
      return vector_uchar( w );
    }
    /**
     * C++ version of gsl_matrix_uchar_const_column().
     * @param j A column index
     * @return A column as a vector_uchar
     */
    vector_uchar const const_column( size_t const j ) const {
      gsl_vector_uchar* w = static_cast<gsl_vector_uchar*>( malloc( sizeof( gsl_vector_uchar ) ) );
      *w = gsl_matrix_uchar_const_column( get(), j ).vector;
      return vector_uchar( w );
    }
    /**
     * C++ version of gsl_matrix_uchar_const_diagonal().
     * @return The principal diagonal as a vector_uchar
     */
    vector_uchar const const_diagonal() const {
      gsl_vector_uchar* w = static_cast<gsl_vector_uchar*>( malloc( sizeof( gsl_vector_uchar ) ) );
      *w = gsl_matrix_uchar_const_diagonal( get() ).vector;
      return vector_uchar( w );
    }
    /**
     * C++ version of gsl_matrix_uchar_const_subdiagonal().
     * @param k An index
     * @return Subdiagonal @c k as a vector_uchar
     */
    vector_uchar const const_subdiagonal( size_t const k ) const {
      gsl_vector_uchar* w = static_cast<gsl_vector_uchar*>( malloc( sizeof( gsl_vector_uchar ) ) );
      *w = gsl_matrix_uchar_const_subdiagonal( get(), k ).vector;
      return vector_uchar( w );
    }
    /**
     * C++ version of gsl_matrix_uchar_const_superdiagonal().
     * @param k An index
     * @return Subdiagonal @c k as a vector_uchar
     */
    vector_uchar const const_superdiagonal( size_t const k ) const {
      gsl_vector_uchar* w = static_cast<gsl_vector_uchar*>( malloc( sizeof( gsl_vector_uchar ) ) );
      *w = gsl_matrix_uchar_const_superdiagonal( get(), k ).vector;
      return vector_uchar( w );
    }
    /**
     * C++ version of gsl_matrix_uchar_const_subrow().
     * @param i A row index
     * @param offset A column offset
     * @param n The number of elements
     * @return A subrow as a vector_uchar
     */
    vector_uchar const const_subrow( size_t const i, size_t const offset, size_t const n ) const {
      gsl_vector_uchar* w = static_cast<gsl_vector_uchar*>( malloc( sizeof( gsl_vector_uchar ) ) );
      *w = gsl_matrix_uchar_const_subrow( get(), i, offset, n ).vector;
      return vector_uchar( w );
    }
    /**
     * C++ version of gsl_matrix_uchar_const_subcolumn().
     * @param j A column index
     * @param offset A row offset
     * @param n The number of elements
     * @return A subcolumn as a vector_uchar
     */
    vector_uchar const const_subcolumn( size_t const j, size_t const offset, size_t const n ) const {
      gsl_vector_uchar* w = static_cast<gsl_vector_uchar*>( malloc( sizeof( gsl_vector_uchar ) ) );
      *w = gsl_matrix_uchar_const_subcolumn( get(), j, offset, n ).vector;
      return vector_uchar( w );
    }
   /**
     * C++ version of gsl_matrix_uchar_const_view_array().
     * @param base An array of type unsigned char
     * @param n1 The number of rows
     * @param n2 The number of columns
     * @return A matrix_uchar
     */
    static matrix_uchar const const_view_array( unsigned char* base, size_t const n1, size_t const n2 ){
      gsl_matrix_uchar* m = static_cast<gsl_matrix_uchar*>( malloc( sizeof( gsl_matrix_uchar ) ) );
      *m = gsl_matrix_uchar_const_view_array( base, n1, n2 ).matrix;
      return matrix_uchar( m );
    }
    /**
     * C++ version of gsl_matrix_uchar_const_view_array_with_tda().
     * @param base An array of type unsigned char
     * @param n1 The number of rows
     * @param n2 The number of columns
     * @param tda The number of columns in memory
     * @return A matrix_uchar
     */
    static matrix_uchar const
    const_view_array_with_tda( unsigned char* base, size_t const n1, size_t const n2, size_t const tda ){
      gsl_matrix_uchar* m = static_cast<gsl_matrix_uchar*>( malloc( sizeof( gsl_matrix_uchar ) ) );
      *m =  gsl_matrix_uchar_const_view_array_with_tda( base, n1, n2, tda ).matrix;
      return matrix_uchar( m );
    }
    /**
     * C++ version of gsl_matrix_uchar_const_view_vector().
     * @param v A vector_uchar
     * @param n1 The number of rows
     * @param n2 The number of columns
     * @return A matrix_uchar
     */
    static matrix_uchar const const_view_vector( vector_uchar& v, size_t const n1, size_t const n2 ){
      gsl_matrix_uchar* m = static_cast<gsl_matrix_uchar*>( malloc( sizeof( gsl_matrix_uchar ) ) );
      *m =  gsl_matrix_uchar_const_view_vector( v.get(), n1, n2 ).matrix;
      return matrix_uchar( m );
    }
    /**
     * C++ version of gsl_matrix_uchar_const_view_vector_with_tda().
     * @param v A vector_uchar
     * @param n1 The number of rows
     * @param n2 The number of columns
     * @param tda The number of columns in memory
     * @return A matrix_uchar
     */
    static matrix_uchar const
    const_view_vector_with_tda( vector_uchar& v, size_t const n1, size_t const n2, size_t const tda ){
      gsl_matrix_uchar* m = static_cast<gsl_matrix_uchar*>( malloc( sizeof( gsl_matrix_uchar ) ) );
      *m = gsl_matrix_uchar_const_view_vector_with_tda( v.get(), n1, n2, tda ).matrix;
      return matrix_uchar( m );
    }
  private:
    /**
     * The shared pointer
     */
    gsl_matrix_uchar* ccgsl_pointer;
    /**
     * The shared reference count
     */
    size_t* count;
  public:
    // shared reference functions
    /**
     * Get the gsl_matrix_uchar.
     * @return the gsl_matrix_uchar
     */
    gsl_matrix_uchar* get(){
#ifndef GSL_RANGE_CHECK_OFF
      if( ccgsl_pointer == 0 )
  	gsl_error( "Object not initialised", __FILE__, __LINE__, exception::GSL_EFAULT );
#endif
      return ccgsl_pointer; }
    /**
     * Get the gsl_matrix_uchar.
     * @return the gsl_matrix_uchar
     */
    gsl_matrix_uchar const* get() const {
#ifndef GSL_RANGE_CHECK_OFF
      if( ccgsl_pointer == 0 )
  	gsl_error( "Object not initialised", __FILE__, __LINE__, exception::GSL_EFAULT );
#endif
      return ccgsl_pointer; }
    /**
     * Find if this is the only object sharing the gsl_matrix_uchar.
     * @return @c true or @c falses according as 
     * this is the only matrix_uchar object sharing the gsl_matrix_uchar
     */
    bool unique() const { return *count == 1; }
    /**
     * Find how many matrix_uchar objects share this pointer.
     * @return the number of matrix_uchar objects that share this pointer
     */
    size_t use_count() const { return *count; }
    /**
     * Allow conversion to bool.
     * @return @c true or @c false according as this contains a pointer
     * to a gsl_matrix_uchar
     */
    operator bool() const { return ccgsl_pointer != 0; }
    // GSL functions
    /**
     * C++ version of gsl_matrix_uchar_calloc(). This constructs a matrix_uchar object with entries
     * initialised to zero.
     * @param n1 The number of rows in the matrix_uchar
     * @param n2 The number of columns in the matrix_uchar
     * @return A matrix_uchar initialised to zero
     */
    static matrix_uchar calloc( size_t const n1, size_t const n2 ){ return matrix_uchar( gsl_matrix_uchar_calloc( n1, n2 ) ); }
    /**
     * C++ version of gsl_matrix_uchar_set_zero().
     */
    void set_zero(){ gsl_matrix_uchar_set_zero( get() ); }
    /**
     * C++ version of gsl_matrix_uchar_set_all().
     * @param x The value to which all elements are set
     */
    void set_all( unsigned char x ){ gsl_matrix_uchar_set_all( get(), x ); }
    /**
     * C++ version of gsl_matrix_uchar_memcpy().
     * @param src source matrix_uchar
     * @return error code on failure
     */
    int memcpy( matrix_uchar const& src ){ return gsl_matrix_uchar_memcpy( get(), src.get() ); }
    /**
     * C++ version of gsl_matrix_uchar_max().
     * @return maximum element of matrix_uchar
     */
    unsigned char max() const { return gsl_matrix_uchar_max( get() ); }
    /**
     * C++ version of gsl_matrix_uchar_min().
     * @return minimum element of matrix_uchar
     */
    unsigned char min() const { return gsl_matrix_uchar_min( get() ); }
    /**
     * C++ version of gsl_matrix_uchar_minmax().
     * @param min_out minimum element of matrix_uchar
     * @param max_out maximum element of matrix_uchar
     */
    void minmax( unsigned char* min_out, unsigned char* max_out ) const {
      gsl_matrix_uchar_minmax( get(), min_out, max_out ); }
    /**
     * C++ version of gsl_matrix_uchar_add().
     * @param b matrix_uchar to add to this
     * @return error code on failure
     */
    int add( matrix_uchar const& b ){ return gsl_matrix_uchar_add( get(), b.get() ); }
    /**
     * C++ version of gsl_matrix_uchar_sub().
     * @param b matrix_uchar to subtract from this
     * @return error code on failure
     */
    int sub( matrix_uchar const& b ){ return gsl_matrix_uchar_sub( get(), b.get() ); }
    /**
     * C++ version of gsl_matrix_uchar_scale().
     * @param x constant to multiply this by
     * @return error code on failure
     */
    int scale( unsigned char const x ){ return gsl_matrix_uchar_scale( get(), x ); }
    /**
     * C++ version of gsl_matrix_uchar_add_constant().
     * @param x constant to add to each element of this
     * @return error code on failure
     */
    int add_constant( unsigned char const x ){ return gsl_matrix_uchar_add_constant( get(), x ); }
    /**
     * C++ version of gsl_matrix_uchar_isnull().
     * @return @c +1 or @c 0 according as elements are all zero or not
     */
    int isnull() const { return gsl_matrix_uchar_isnull( get() ); }
    /**
     * C++ version of gsl_matrix_uchar_ispos().
     * @return @c +1 or @c 0 according as elements are all positive or not
     */
    int ispos() const { return gsl_matrix_uchar_ispos( get() ); }
    /**
     * C++ version of gsl_matrix_uchar_isneg().
     * @return @c +1 or @c 0 according as elements are all negative or not
     */
    int isneg() const { return gsl_matrix_uchar_isneg( get() ); }
    /**
     * C++ version of gsl_matrix_uchar_isnonneg().
     * @return @c +1 or @c 0 according as elements are all nonnegative or not
     */
    int isnonneg() const { return gsl_matrix_uchar_isnonneg( get() ); }
    /**
     * C++ version of gsl_matrix_uchar_get().
     * @param i index of row
     * @param j index of column
     * @return value of element
     */
    unsigned char get( size_t const i, size_t const j ) const { return gsl_matrix_uchar_get( get(), i, j ); }
    /**
     * C++ version of gsl_matrix_uchar_set().
     * @param i index of row
     * @param j index of column
     * @param x new value for element
     */
    void set( size_t const i, size_t const j, unsigned char x ){ gsl_matrix_uchar_set( get(), i, j, x ); }
    /**
     * C++ version of gsl_matrix_uchar_ptr().
     * @param i index of row
     * @param j index of column
     * @return pointer to element
     */
    unsigned char* ptr( size_t const i, size_t const j ){ return gsl_matrix_uchar_ptr( get(), i, j ); }
    /**
     * C++ version of gsl_matrix_uchar_const_ptr().
     * @param i index of row
     * @param j index of column
     * @return pointer to element
     */
    unsigned char const* const_ptr( size_t const i, size_t const j ) const {
      return gsl_matrix_uchar_const_ptr( get(), i, j ); }
    /**
     * C++ version of gsl_matrix_uchar_fread().
     * @param stream A C file stream
     * @return error code on failure
     */
    int fread( FILE* stream ){ return gsl_matrix_uchar_fread( stream, get() ); }
    /**
     * C++ version of gsl_matrix_uchar_fwrite().
     * @param stream A C file stream
     * @return error code on failure
     */
    int fwrite( FILE* stream ) const { return gsl_matrix_uchar_fwrite( stream, get() ); }
    /**
     * C++ version of gsl_matrix_uchar_fscanf().
     * @param stream A C file stream
     * @return error code on failure
     */
    int fscanf( FILE* stream ){ return gsl_matrix_uchar_fscanf( stream, get() ); }
    /**
     * C++ version of gsl_matrix_uchar_fprintf().
     * @param stream A C file stream
     * @param format %d, %e, %f or %g
     * @return error code on failure
     */
    int fprintf( FILE* stream, char const* format ) const {
      return gsl_matrix_uchar_fprintf( stream, get(), format ); }
    /**
     * C++ version of gsl_matrix_uchar_alloc_from_block().
     * @param b The block_uchar
     * @param offset The offset within the block_uchar
     * @param n1 The number of rows in the matrix_uchar
     * @param n2 The number of columns in the matrix_uchar
     * @param d2 undocumented
     */
    matrix_uchar( block_uchar& b, size_t const offset, size_t const n1, size_t const n2, size_t const d2 ){
      ccgsl_pointer = gsl_matrix_uchar_alloc_from_block( b.get(), offset, n1, n2, d2 );
      // just plausibly we could allocate vector_uchar but not count
      try { count = new size_t; } catch( std::bad_alloc& e ){
    	// try to tidy up before rethrowing
    	gsl_matrix_uchar_free( ccgsl_pointer );
    	throw e;
      }
      *count = 1; // initially there is just one reference to ccgsl_pointer
    }
    /**
     * C++ version of gsl_matrix_uchar_alloc_from_matrix().
     * @param m The matrix_uchar
     * @param k1 the row of @c m to take as row zero
     * @param k2 the column of @c m to take as column zero
     * @param n1 The number of rows in the matrix_uchar
     * @param n2 The number of columns in the matrix_uchar
     */
    matrix_uchar( matrix_uchar& m, size_t const k1, size_t const k2, size_t const n1, size_t const n2 ){
      ccgsl_pointer = gsl_matrix_uchar_alloc_from_matrix( m.get(), k1, k2, n1, n2 );
      // just plausibly we could allocate matrix_uchar but not count
      try { count = new size_t; } catch( std::bad_alloc& e ){
    	// try to tidy up before rethrowing
    	gsl_matrix_uchar_free( ccgsl_pointer );
    	throw e;
      }
      *count = 1; // initially there is just one reference to ccgsl_pointer
    }
    // More functions
    /**
     * C++ version of gsl_matrix_uchar_set_identity().
     */
    void set_identity(){ gsl_matrix_uchar_set_identity( get() ); }
    /**
     * C++ version of gsl_matrix_uchar_swap_rows().
     * @param i Index of first row
     * @param j Index of second row
     * @return error code on failure
     */
    int swap_rows( size_t const i, size_t const j ){ return gsl_matrix_uchar_swap_rows( get(), i, j ); }
    /**
     * C++ version of gsl_matrix_uchar_swap_columns().
     * @param i Index of first column
     * @param j Index of second column
     * @return error code on failure
     */
    int swap_columns( size_t const i, size_t const j ){
      return gsl_matrix_uchar_swap_columns( get(), i, j ); }
    /**
     * C++ version of gsl_matrix_uchar_swap_rowcol(). Swap row and column in place. Matrix must be square.
     * @param i index of row
     * @param j index of column
     * @return error code on failure
     */
    int swap_rowcol( size_t const i, size_t const j ){ return gsl_matrix_uchar_swap_rowcol( get(), i, j ); }
    /**
     * C++ version of gsl_matrix_uchar_transpose().
     * @return error code on failure.
     */
    int transpose(){ return gsl_matrix_uchar_transpose( get() ); }
    /**
     * C++ version of gsl_matrix_uchar_transpose_memcpy().
     * @param src matrix_uchar whose transpose it to be copied to @c this
     * @return error code on failure
     */
    int transpose_memcpy( matrix_uchar const& src ){
      return gsl_matrix_uchar_transpose_memcpy( get(), src.get() ); }
    /**
     * C++ version of gsl_matrix_uchar_max_index().
     * @param imax row index of the first maximum element in the matrix_uchar
     * @param jmax column index of the first maximum element in the matrix_uchar
     */
    void max_index( size_t* imax, size_t* jmax ) const {
      gsl_matrix_uchar_max_index( get(), imax, jmax ); }
    /**
     * C++ version of gsl_matrix_uchar_min_index().
     * @param imin row index of the first minimum element in the matrix_uchar
     * @param jmin column index of the first minimum element in the matrix_uchar
     */
    void min_index( size_t* imin, size_t* jmin ) const {
      gsl_matrix_uchar_min_index( get(), imin, jmin ); }
    /**
     * C++ version of gsl_matrix_uchar_minmax_index().
     * @param imin row index of the first minimum element in the matrix_uchar
     * @param jmin column index of the first minimum element in the matrix_uchar
     * @param imax row index of the first maximum element in the matrix_uchar
     * @param jmax column index of the first maximum element in the matrix_uchar
     */
    void minmax_index( size_t* imin, size_t* jmin, size_t* imax, size_t* jmax ) const {
      gsl_matrix_uchar_minmax_index( get(), imin, jmin, imax, jmax ); }
    /**
     * C++ version of gsl_matrix_uchar_mul_elements(). Multiply matrices elementwise.
     * @param b Another matrix_uchar
     * @return error code on failure
     */
    int
    mul_elements( matrix_uchar const& b ){
          return gsl_matrix_uchar_mul_elements( get(), b.get() ); }
    /**
     * C++ version of gsl_matrix_uchar_div_elements(). Divide each element of @c this by the
     * corrsponding element of @c b
     * @param b Another matrix_uchar
     * @return error code on failure
     */
    int div_elements( matrix_uchar const& b ){
      return gsl_matrix_uchar_div_elements( get(), b.get() ); }
    /**
     * C++ version of gsl_matrix_uchar_add_diagonal().
     * @param x A constant
     * @return error code on failure
     */
    int add_diagonal( unsigned char const x ){
      return gsl_matrix_uchar_add_diagonal( get(), x ); }
    /**
     * C++ version of gsl_matrix_uchar_get_row().
     * @param v A vector_uchar
     * @param i The index of the row
     * @return error code on failure
     */
    int get_row( vector_uchar& v, size_t const i ) const {
      return gsl_matrix_uchar_get_row( v.get(), get(), i ); }
    /**
     * C++ version of gsl_matrix_uchar_get_col().
     * @param v A vector_uchar
     * @param j The index of the column
     * @return error code on failure
     */
    int get_col( vector_uchar& v, size_t const j ) const {
      return gsl_matrix_uchar_get_col( v.get(), get(), j ); }
    /**
     * C++ version of gsl_matrix_uchar_set_row().
     * @param i The index of the row
     * @param v A vector_uchar
     * @return error code on failure
     */
    int set_row( size_t const i, vector_uchar const& v ){
      return gsl_matrix_uchar_set_row( get(), i, v.get() ); }
    /**
     * C++ version of gsl_matrix_uchar_set_col().
     * @param j The index of the column
     * @param v A vector_uchar
     * @return error code on failure
     */
    int set_col( size_t const j, vector_uchar const& v ){
      return gsl_matrix_uchar_set_col( get(), j, v.get() ); }
    // Extra functions for []
    /**
     * This function allows us to use a matrix_uchar like an array. Use with caution.
     * Although @c matrix_uchar[i][j] is possible, it is much less efficient than
     * matrix_uchar::set(). The effect is the same as row()
     * @param i The index of the row
     * @return A vector_uchar representing a row
     */
    vector_uchar operator[]( size_t const i ){
      // First check that iterator is initialised.
      if( ccgsl_pointer == 0 ){
  	gsl_error( "matrix_uchar is null", __FILE__, __LINE__, exception::GSL_EFAILED );
  	return vector_uchar();
      }
      gsl_vector_uchar* w = static_cast<gsl_vector_uchar*>( malloc( sizeof( gsl_vector_uchar ) ) );
      *w = gsl_matrix_uchar_row( ccgsl_pointer, i ).vector;
      return vector_uchar( w );
    }
    /**
     * This function allows us to use a matrix_uchar like an array. Use with caution.
     * Although @c matrix_uchar[i][j] is possible, it is much less efficient than
     * matrix_uchar::set(). The effect is the same as row()
     * @param i The index of the row
     * @return A vector_uchar representing a row
     */
    vector_uchar const operator[]( size_t const i ) const {
      // First check that iterator is initialised.
      if( ccgsl_pointer == 0 ){
  	gsl_error( "matrix_uchar is null", __FILE__, __LINE__, exception::GSL_EFAILED );
  	return vector_uchar();
      }
      gsl_vector_uchar* w = static_cast<gsl_vector_uchar*>( malloc( sizeof( gsl_vector_uchar ) ) );
      *w = gsl_matrix_uchar_row( ccgsl_pointer, i ).vector;
      return vector_uchar( w );
    }
  };

  // Extra functions for vector_uchar allocation from matrix_uchar objects
  vector_uchar vector_uchar::alloc_row_from_matrix( matrix_uchar& m, size_t const i ){
    return vector_uchar ( gsl_vector_uchar_alloc_row_from_matrix( m.get(), i ) ); }
   vector_uchar vector_uchar::alloc_col_from_matrix( matrix_uchar& m, size_t const i ){
    return vector_uchar ( gsl_vector_uchar_alloc_col_from_matrix( m.get(), i ) ); }
}
#endif
