/*
 * Copyright (C) 2010 John D Lamb
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or (at
 * your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

#ifndef CCGSL_MATRIX_UINT_HPP
#define CCGSL_MATRIX_UINT_HPP

#include<gsl/gsl_matrix.h>
#include<new>

#include"exception.hpp"
#include"vector_uint.hpp"

// This file is autogenerated

namespace gsl {
  /**
   * This class handles matrix_uint objects as shared handles. It models a random access container
   * so that STL functions work with matrix_uint.
   *
   * Note that matrix_uint_views are implemented as matrix_uint objects here.
   */
  class matrix_uint {
  public:
    /**
     * The default constructor is only really useful for assigning to.
     */
    matrix_uint(){
      ccgsl_pointer = 0;
      // just plausibly we could fail to allocate count
      try { count = new size_t; } catch( std::bad_alloc& e ){
	throw e;
      }
      *count = 1; // initially there is just one reference to ccgsl_pointer
    }
    // Refines random access container
    // Refines assignable
    /**
     * The default constructor creates a new matrix_uint with n elements
     * @param n1 The number of rows in the matrix_uint
     * @param n2 The number of columns in the matrix_uint
     */
    explicit matrix_uint( size_t const n1, size_t const n2 ){
      ccgsl_pointer = gsl_matrix_uint_alloc( n1, n2 );
      // just plausibly we could allocate matrix_uint but not count
      try { count = new size_t; } catch( std::bad_alloc& e ){
	// try to tidy up before rethrowing
	gsl_matrix_uint_free( ccgsl_pointer );
	throw e;
      }
      *count = 1; // initially there is just one reference to ccgsl_pointer
    }
    /**
     * Could construct from a gsl_matrix_uint. This is not usually a good idea. In this case
     * we should not use gsl_matrix_uint_free() to deallocate the memory.
     * @param v The matrix_uint
     */
    explicit matrix_uint( gsl_matrix_uint* v ){
      ccgsl_pointer = v;
      // just plausibly we could fail to allocate count: no further action needed.
      count = new size_t;
      *count = 1; // initially there is just one reference to ccgsl_pointer
    }
    // copy constructor
    /**
     * The copy constructor. This shares the matrix_uint. Use clone() if you want a full copy.
     * @param v The matrix_uint to copy.
     */
    matrix_uint( matrix_uint const& v ) : ccgsl_pointer( v.ccgsl_pointer ), count( v.count ){
      ++*count; // matrix_uint is now shared.
    }
    // assignment operator
    /**
     * The assignment operator. This makes a shared copy.
     * @param v The matrix_uint to copy
     */
    matrix_uint& operator=( matrix_uint const& v ){
      // first, possibly delete anything pointed to by this
      if( --*count == 0 ){
	if( ccgsl_pointer != 0 ) gsl_matrix_uint_free( ccgsl_pointer );
	delete count;
      }
      // Then copy
      ccgsl_pointer = v.ccgsl_pointer;
      count = v.count;
      ++*count; // block_uint is now shared.
      return *this;
    }
    // clone()
    /**
     * The clone function. Use this if you want a copy of the block_uint that does
     * not share the underlying data.
     * @return a new copy of this.
     */
    matrix_uint clone() const {
      matrix_uint copy( get()->size1, get()->size2 );
      // Now copy
      gsl_matrix_uint_memcpy( copy.get(), get() );
      // return new object
      return copy;
    }
    // destructor
    /**
     * The destructor only deletes the pointers if count reaches zero.
     */
    ~matrix_uint(){
      if( --*count == 0 ){
	// could have allocated null pointer
	if( ccgsl_pointer != 0 ) gsl_matrix_uint_free( ccgsl_pointer );
	delete count;
      }
    }
    // Sizes
    /**
     * The number of rows of the matrix_uint
     * @return The number of rows of the matrix_uint
     */
    size_t size1() const { return ccgsl_pointer == 0 ? 0 : ccgsl_pointer->size1; }
    /**
     * The number of columns of the matrix_uint
     * @return The number of columns of the matrix_uint
     */
    size_t size2() const { return ccgsl_pointer == 0 ? 0 : ccgsl_pointer->size2; }
    /**
     * Swap two matrix_uint objects. This works even if the matrix_uint objects have different sizes
     * because it swaps pointers.
     * @param m The matrix_uint to swap with @c this.
     */
    void swap( matrix_uint& m ){
      gsl_matrix_uint* tmp = ccgsl_pointer; ccgsl_pointer = m.ccgsl_pointer; m.ccgsl_pointer = tmp;
      size_t* tmp2 = count; count = m.count; m.count = tmp2;
    }
    // view operations
    /**
     * C++ version of gsl_matrix_uint_submatrix().
     * @param i Index in @c this of first row of submatrix
     * @param j Index in @c this of first column of submatrix
     * @param n1 Number of rows of submatrix
     * @param n2 Number of columns of submatrix
     * @return The submatrix
     */
    matrix_uint submatrix( size_t const i, size_t const j, size_t const n1, size_t const n2 ){
      gsl_matrix_uint* m = static_cast<gsl_matrix_uint*>( malloc( sizeof( gsl_matrix_uint ) ) );
      *m = gsl_matrix_uint_submatrix( get(), i, j, n1, n2 ).matrix;
      return matrix_uint( m );
    }
    /**
     * C++ version of gsl_matrix_uint_row().
     * @param i A row index
     * @return A row as a vector_uint
     */
    vector_uint row( size_t const i ){
      gsl_vector_uint* w = static_cast<gsl_vector_uint*>( malloc( sizeof( gsl_vector_uint ) ) );
      *w = gsl_matrix_uint_row( get(), i ).vector;
      return vector_uint( w );
    }
    /**
     * C++ version of gsl_matrix_uint_column().
     * @param j A column index
     * @return A column as a vector_uint
     */
    vector_uint column( size_t const j ){
      gsl_vector_uint* w = static_cast<gsl_vector_uint*>( malloc( sizeof( gsl_vector_uint ) ) );
      *w = gsl_matrix_uint_column( get(), j ).vector;
      return vector_uint( w );
    }
    /**
     * C++ version of gsl_matrix_uint_diagonal().
     * @return The principal diagonal as a vector_uint
     */
    vector_uint
    diagonal(){ gsl_vector_uint* w = static_cast<gsl_vector_uint*>( malloc( sizeof( gsl_vector_uint ) ) );
      *w = gsl_matrix_uint_diagonal( get() ).vector;
      return vector_uint( w );
    }
    /**
     * C++ version of gsl_matrix_uint_subdiagonal().
     * @param k An index
     * @return Subdiagonal @c k as a vector_uint
     */
    vector_uint subdiagonal( size_t const k ){
      gsl_vector_uint* w = static_cast<gsl_vector_uint*>( malloc( sizeof( gsl_vector_uint ) ) );
      *w = gsl_matrix_uint_subdiagonal( get(), k ).vector;
      return vector_uint( w );
    }
    /**
     * C++ version of gsl_matrix_uint_superdiagonal().
     * @param k An index
     * @return Subdiagonal @c k as a vector_uint
     */
    vector_uint superdiagonal( size_t const k ){
      gsl_vector_uint* w = static_cast<gsl_vector_uint*>( malloc( sizeof( gsl_vector_uint ) ) );
      *w = gsl_matrix_uint_superdiagonal( get(), k ).vector;
      return vector_uint( w );
    }
    /**
     * C++ version of gsl_matrix_uint_subrow().
     * @param i A row index
     * @param offset A column offset
     * @param n The number of elements
     * @return A subrow as a vector_uint
     */
    vector_uint subrow( size_t const i, size_t const offset, size_t const n ){
      gsl_vector_uint* w = static_cast<gsl_vector_uint*>( malloc( sizeof( gsl_vector_uint ) ) );
      *w = gsl_matrix_uint_subrow( get(), i, offset, n ).vector;
      return vector_uint( w );
    }
    /**
     * C++ version of gsl_matrix_uint_subcolumn().
     * @param j A column index
     * @param offset A row offset
     * @param n The number of elements
     * @return A subcolumn as a vector_uint
     */
    vector_uint subcolumn( size_t const j, size_t const offset, size_t const n ){
      gsl_vector_uint* w = static_cast<gsl_vector_uint*>( malloc( sizeof( gsl_vector_uint ) ) );
      *w = gsl_matrix_uint_subcolumn( get(), j, offset, n ).vector;
      return vector_uint( w );
    }
   /**
     * C++ version of gsl_matrix_uint_view_array().
     * @param base An array of type unsigned int
     * @param n1 The number of rows
     * @param n2 The number of columns
     * @return A matrix_uint
     */
    static matrix_uint view_array( unsigned int* base, size_t const n1, size_t const n2 ){
      gsl_matrix_uint* m = static_cast<gsl_matrix_uint*>( malloc( sizeof( gsl_matrix_uint ) ) );
      *m = gsl_matrix_uint_view_array( base, n1, n2 ).matrix;
      return matrix_uint( m );
    }
    /**
     * C++ version of gsl_matrix_uint_view_array_with_tda().
     * @param base An array of type unsigned int
     * @param n1 The number of rows
     * @param n2 The number of columns
     * @param tda The number of columns in memory
     * @return A matrix_uint
     */
    static matrix_uint view_array_with_tda( unsigned int* base, size_t const n1, size_t const n2, size_t const tda ){
      gsl_matrix_uint* m = static_cast<gsl_matrix_uint*>( malloc( sizeof( gsl_matrix_uint ) ) );
      *m =  gsl_matrix_uint_view_array_with_tda( base, n1, n2, tda ).matrix;
      return matrix_uint( m );
    }
    /**
     * C++ version of gsl_matrix_uint_view_vector().
     * @param v A vector_uint
     * @param n1 The number of rows
     * @param n2 The number of columns
     * @return A matrix_uint
     */
    static matrix_uint view_vector( vector_uint& v, size_t const n1, size_t const n2 ){
      gsl_matrix_uint* m = static_cast<gsl_matrix_uint*>( malloc( sizeof( gsl_matrix_uint ) ) );
      *m =  gsl_matrix_uint_view_vector( v.get(), n1, n2 ).matrix;
      return matrix_uint( m );
    }
    /**
     * C++ version of gsl_matrix_uint_view_vector_with_tda().
     * @param v A vector_uint
     * @param n1 The number of rows
     * @param n2 The number of columns
     * @param tda The number of columns in memory
     * @return A matrix_uint
     */
    static matrix_uint view_vector_with_tda( vector_uint& v, size_t const n1, size_t const n2, size_t const tda ){
      gsl_matrix_uint* m = static_cast<gsl_matrix_uint*>( malloc( sizeof( gsl_matrix_uint ) ) );
      *m = gsl_matrix_uint_view_vector_with_tda( v.get(), n1, n2, tda ).matrix;
      return matrix_uint( m );
    }
    // const versions ...
    /**
     * C++ version of gsl_matrix_uint_const_submatrix().
     * @param i Index in @c this of first row of submatrix
     * @param j Index in @c this of first column of submatrix
     * @param n1 Number of rows of submatrix
     * @param n2 Number of columns of submatrix
     * @return The submatrix
     */
    matrix_uint const const_submatrix( size_t const i, size_t const j, size_t const n1, size_t const n2 ) const {
      gsl_matrix_uint* m = static_cast<gsl_matrix_uint*>( malloc( sizeof( gsl_matrix_uint ) ) );
      *m = gsl_matrix_uint_const_submatrix( get(), i, j, n1, n2 ).matrix;
      return matrix_uint( m );
    }
    /**
     * C++ version of gsl_matrix_uint_const_row().
     * @param i A row index
     * @return A row as a vector_uint
     */
    vector_uint const const_row( size_t const i ) const {
      gsl_vector_uint* w = static_cast<gsl_vector_uint*>( malloc( sizeof( gsl_vector_uint ) ) );
      *w = gsl_matrix_uint_const_row( get(), i ).vector;
      return vector_uint( w );
    }
    /**
     * C++ version of gsl_matrix_uint_const_column().
     * @param j A column index
     * @return A column as a vector_uint
     */
    vector_uint const const_column( size_t const j ) const {
      gsl_vector_uint* w = static_cast<gsl_vector_uint*>( malloc( sizeof( gsl_vector_uint ) ) );
      *w = gsl_matrix_uint_const_column( get(), j ).vector;
      return vector_uint( w );
    }
    /**
     * C++ version of gsl_matrix_uint_const_diagonal().
     * @return The principal diagonal as a vector_uint
     */
    vector_uint const const_diagonal() const {
      gsl_vector_uint* w = static_cast<gsl_vector_uint*>( malloc( sizeof( gsl_vector_uint ) ) );
      *w = gsl_matrix_uint_const_diagonal( get() ).vector;
      return vector_uint( w );
    }
    /**
     * C++ version of gsl_matrix_uint_const_subdiagonal().
     * @param k An index
     * @return Subdiagonal @c k as a vector_uint
     */
    vector_uint const const_subdiagonal( size_t const k ) const {
      gsl_vector_uint* w = static_cast<gsl_vector_uint*>( malloc( sizeof( gsl_vector_uint ) ) );
      *w = gsl_matrix_uint_const_subdiagonal( get(), k ).vector;
      return vector_uint( w );
    }
    /**
     * C++ version of gsl_matrix_uint_const_superdiagonal().
     * @param k An index
     * @return Subdiagonal @c k as a vector_uint
     */
    vector_uint const const_superdiagonal( size_t const k ) const {
      gsl_vector_uint* w = static_cast<gsl_vector_uint*>( malloc( sizeof( gsl_vector_uint ) ) );
      *w = gsl_matrix_uint_const_superdiagonal( get(), k ).vector;
      return vector_uint( w );
    }
    /**
     * C++ version of gsl_matrix_uint_const_subrow().
     * @param i A row index
     * @param offset A column offset
     * @param n The number of elements
     * @return A subrow as a vector_uint
     */
    vector_uint const const_subrow( size_t const i, size_t const offset, size_t const n ) const {
      gsl_vector_uint* w = static_cast<gsl_vector_uint*>( malloc( sizeof( gsl_vector_uint ) ) );
      *w = gsl_matrix_uint_const_subrow( get(), i, offset, n ).vector;
      return vector_uint( w );
    }
    /**
     * C++ version of gsl_matrix_uint_const_subcolumn().
     * @param j A column index
     * @param offset A row offset
     * @param n The number of elements
     * @return A subcolumn as a vector_uint
     */
    vector_uint const const_subcolumn( size_t const j, size_t const offset, size_t const n ) const {
      gsl_vector_uint* w = static_cast<gsl_vector_uint*>( malloc( sizeof( gsl_vector_uint ) ) );
      *w = gsl_matrix_uint_const_subcolumn( get(), j, offset, n ).vector;
      return vector_uint( w );
    }
   /**
     * C++ version of gsl_matrix_uint_const_view_array().
     * @param base An array of type unsigned int
     * @param n1 The number of rows
     * @param n2 The number of columns
     * @return A matrix_uint
     */
    static matrix_uint const const_view_array( unsigned int* base, size_t const n1, size_t const n2 ){
      gsl_matrix_uint* m = static_cast<gsl_matrix_uint*>( malloc( sizeof( gsl_matrix_uint ) ) );
      *m = gsl_matrix_uint_const_view_array( base, n1, n2 ).matrix;
      return matrix_uint( m );
    }
    /**
     * C++ version of gsl_matrix_uint_const_view_array_with_tda().
     * @param base An array of type unsigned int
     * @param n1 The number of rows
     * @param n2 The number of columns
     * @param tda The number of columns in memory
     * @return A matrix_uint
     */
    static matrix_uint const
    const_view_array_with_tda( unsigned int* base, size_t const n1, size_t const n2, size_t const tda ){
      gsl_matrix_uint* m = static_cast<gsl_matrix_uint*>( malloc( sizeof( gsl_matrix_uint ) ) );
      *m =  gsl_matrix_uint_const_view_array_with_tda( base, n1, n2, tda ).matrix;
      return matrix_uint( m );
    }
    /**
     * C++ version of gsl_matrix_uint_const_view_vector().
     * @param v A vector_uint
     * @param n1 The number of rows
     * @param n2 The number of columns
     * @return A matrix_uint
     */
    static matrix_uint const const_view_vector( vector_uint& v, size_t const n1, size_t const n2 ){
      gsl_matrix_uint* m = static_cast<gsl_matrix_uint*>( malloc( sizeof( gsl_matrix_uint ) ) );
      *m =  gsl_matrix_uint_const_view_vector( v.get(), n1, n2 ).matrix;
      return matrix_uint( m );
    }
    /**
     * C++ version of gsl_matrix_uint_const_view_vector_with_tda().
     * @param v A vector_uint
     * @param n1 The number of rows
     * @param n2 The number of columns
     * @param tda The number of columns in memory
     * @return A matrix_uint
     */
    static matrix_uint const
    const_view_vector_with_tda( vector_uint& v, size_t const n1, size_t const n2, size_t const tda ){
      gsl_matrix_uint* m = static_cast<gsl_matrix_uint*>( malloc( sizeof( gsl_matrix_uint ) ) );
      *m = gsl_matrix_uint_const_view_vector_with_tda( v.get(), n1, n2, tda ).matrix;
      return matrix_uint( m );
    }
  private:
    /**
     * The shared pointer
     */
    gsl_matrix_uint* ccgsl_pointer;
    /**
     * The shared reference count
     */
    size_t* count;
  public:
    // shared reference functions
    /**
     * Get the gsl_matrix_uint.
     * @return the gsl_matrix_uint
     */
    gsl_matrix_uint* get(){
#ifndef GSL_RANGE_CHECK_OFF
      if( ccgsl_pointer == 0 )
  	gsl_error( "Object not initialised", __FILE__, __LINE__, exception::GSL_EFAULT );
#endif
      return ccgsl_pointer; }
    /**
     * Get the gsl_matrix_uint.
     * @return the gsl_matrix_uint
     */
    gsl_matrix_uint const* get() const {
#ifndef GSL_RANGE_CHECK_OFF
      if( ccgsl_pointer == 0 )
  	gsl_error( "Object not initialised", __FILE__, __LINE__, exception::GSL_EFAULT );
#endif
      return ccgsl_pointer; }
    /**
     * Find if this is the only object sharing the gsl_matrix_uint.
     * @return @c true or @c falses according as 
     * this is the only matrix_uint object sharing the gsl_matrix_uint
     */
    bool unique() const { return *count == 1; }
    /**
     * Find how many matrix_uint objects share this pointer.
     * @return the number of matrix_uint objects that share this pointer
     */
    size_t use_count() const { return *count; }
    /**
     * Allow conversion to bool.
     * @return @c true or @c false according as this contains a pointer
     * to a gsl_matrix_uint
     */
    operator bool() const { return ccgsl_pointer != 0; }
    // GSL functions
    /**
     * C++ version of gsl_matrix_uint_calloc(). This constructs a matrix_uint object with entries
     * initialised to zero.
     * @param n1 The number of rows in the matrix_uint
     * @param n2 The number of columns in the matrix_uint
     * @return A matrix_uint initialised to zero
     */
    static matrix_uint calloc( size_t const n1, size_t const n2 ){ return matrix_uint( gsl_matrix_uint_calloc( n1, n2 ) ); }
    /**
     * C++ version of gsl_matrix_uint_set_zero().
     */
    void set_zero(){ gsl_matrix_uint_set_zero( get() ); }
    /**
     * C++ version of gsl_matrix_uint_set_all().
     * @param x The value to which all elements are set
     */
    void set_all( unsigned int x ){ gsl_matrix_uint_set_all( get(), x ); }
    /**
     * C++ version of gsl_matrix_uint_memcpy().
     * @param src source matrix_uint
     * @return error code on failure
     */
    int memcpy( matrix_uint const& src ){ return gsl_matrix_uint_memcpy( get(), src.get() ); }
    /**
     * C++ version of gsl_matrix_uint_max().
     * @return maximum element of matrix_uint
     */
    unsigned int max() const { return gsl_matrix_uint_max( get() ); }
    /**
     * C++ version of gsl_matrix_uint_min().
     * @return minimum element of matrix_uint
     */
    unsigned int min() const { return gsl_matrix_uint_min( get() ); }
    /**
     * C++ version of gsl_matrix_uint_minmax().
     * @param min_out minimum element of matrix_uint
     * @param max_out maximum element of matrix_uint
     */
    void minmax( unsigned int* min_out, unsigned int* max_out ) const {
      gsl_matrix_uint_minmax( get(), min_out, max_out ); }
    /**
     * C++ version of gsl_matrix_uint_add().
     * @param b matrix_uint to add to this
     * @return error code on failure
     */
    int add( matrix_uint const& b ){ return gsl_matrix_uint_add( get(), b.get() ); }
    /**
     * C++ version of gsl_matrix_uint_sub().
     * @param b matrix_uint to subtract from this
     * @return error code on failure
     */
    int sub( matrix_uint const& b ){ return gsl_matrix_uint_sub( get(), b.get() ); }
    /**
     * C++ version of gsl_matrix_uint_scale().
     * @param x constant to multiply this by
     * @return error code on failure
     */
    int scale( unsigned int const x ){ return gsl_matrix_uint_scale( get(), x ); }
    /**
     * C++ version of gsl_matrix_uint_add_constant().
     * @param x constant to add to each element of this
     * @return error code on failure
     */
    int add_constant( unsigned int const x ){ return gsl_matrix_uint_add_constant( get(), x ); }
    /**
     * C++ version of gsl_matrix_uint_isnull().
     * @return @c +1 or @c 0 according as elements are all zero or not
     */
    int isnull() const { return gsl_matrix_uint_isnull( get() ); }
    /**
     * C++ version of gsl_matrix_uint_ispos().
     * @return @c +1 or @c 0 according as elements are all positive or not
     */
    int ispos() const { return gsl_matrix_uint_ispos( get() ); }
    /**
     * C++ version of gsl_matrix_uint_isneg().
     * @return @c +1 or @c 0 according as elements are all negative or not
     */
    int isneg() const { return gsl_matrix_uint_isneg( get() ); }
    /**
     * C++ version of gsl_matrix_uint_isnonneg().
     * @return @c +1 or @c 0 according as elements are all nonnegative or not
     */
    int isnonneg() const { return gsl_matrix_uint_isnonneg( get() ); }
    /**
     * C++ version of gsl_matrix_uint_get().
     * @param i index of row
     * @param j index of column
     * @return value of element
     */
    unsigned int get( size_t const i, size_t const j ) const { return gsl_matrix_uint_get( get(), i, j ); }
    /**
     * C++ version of gsl_matrix_uint_set().
     * @param i index of row
     * @param j index of column
     * @param x new value for element
     */
    void set( size_t const i, size_t const j, unsigned int x ){ gsl_matrix_uint_set( get(), i, j, x ); }
    /**
     * C++ version of gsl_matrix_uint_ptr().
     * @param i index of row
     * @param j index of column
     * @return pointer to element
     */
    unsigned int* ptr( size_t const i, size_t const j ){ return gsl_matrix_uint_ptr( get(), i, j ); }
    /**
     * C++ version of gsl_matrix_uint_const_ptr().
     * @param i index of row
     * @param j index of column
     * @return pointer to element
     */
    unsigned int const* const_ptr( size_t const i, size_t const j ) const {
      return gsl_matrix_uint_const_ptr( get(), i, j ); }
    /**
     * C++ version of gsl_matrix_uint_fread().
     * @param stream A C file stream
     * @return error code on failure
     */
    int fread( FILE* stream ){ return gsl_matrix_uint_fread( stream, get() ); }
    /**
     * C++ version of gsl_matrix_uint_fwrite().
     * @param stream A C file stream
     * @return error code on failure
     */
    int fwrite( FILE* stream ) const { return gsl_matrix_uint_fwrite( stream, get() ); }
    /**
     * C++ version of gsl_matrix_uint_fscanf().
     * @param stream A C file stream
     * @return error code on failure
     */
    int fscanf( FILE* stream ){ return gsl_matrix_uint_fscanf( stream, get() ); }
    /**
     * C++ version of gsl_matrix_uint_fprintf().
     * @param stream A C file stream
     * @param format %d, %e, %f or %g
     * @return error code on failure
     */
    int fprintf( FILE* stream, char const* format ) const {
      return gsl_matrix_uint_fprintf( stream, get(), format ); }
    /**
     * C++ version of gsl_matrix_uint_alloc_from_block().
     * @param b The block_uint
     * @param offset The offset within the block_uint
     * @param n1 The number of rows in the matrix_uint
     * @param n2 The number of columns in the matrix_uint
     * @param d2 undocumented
     */
    matrix_uint( block_uint& b, size_t const offset, size_t const n1, size_t const n2, size_t const d2 ){
      ccgsl_pointer = gsl_matrix_uint_alloc_from_block( b.get(), offset, n1, n2, d2 );
      // just plausibly we could allocate vector_uint but not count
      try { count = new size_t; } catch( std::bad_alloc& e ){
    	// try to tidy up before rethrowing
    	gsl_matrix_uint_free( ccgsl_pointer );
    	throw e;
      }
      *count = 1; // initially there is just one reference to ccgsl_pointer
    }
    /**
     * C++ version of gsl_matrix_uint_alloc_from_matrix().
     * @param m The matrix_uint
     * @param k1 the row of @c m to take as row zero
     * @param k2 the column of @c m to take as column zero
     * @param n1 The number of rows in the matrix_uint
     * @param n2 The number of columns in the matrix_uint
     */
    matrix_uint( matrix_uint& m, size_t const k1, size_t const k2, size_t const n1, size_t const n2 ){
      ccgsl_pointer = gsl_matrix_uint_alloc_from_matrix( m.get(), k1, k2, n1, n2 );
      // just plausibly we could allocate matrix_uint but not count
      try { count = new size_t; } catch( std::bad_alloc& e ){
    	// try to tidy up before rethrowing
    	gsl_matrix_uint_free( ccgsl_pointer );
    	throw e;
      }
      *count = 1; // initially there is just one reference to ccgsl_pointer
    }
    // More functions
    /**
     * C++ version of gsl_matrix_uint_set_identity().
     */
    void set_identity(){ gsl_matrix_uint_set_identity( get() ); }
    /**
     * C++ version of gsl_matrix_uint_swap_rows().
     * @param i Index of first row
     * @param j Index of second row
     * @return error code on failure
     */
    int swap_rows( size_t const i, size_t const j ){ return gsl_matrix_uint_swap_rows( get(), i, j ); }
    /**
     * C++ version of gsl_matrix_uint_swap_columns().
     * @param i Index of first column
     * @param j Index of second column
     * @return error code on failure
     */
    int swap_columns( size_t const i, size_t const j ){
      return gsl_matrix_uint_swap_columns( get(), i, j ); }
    /**
     * C++ version of gsl_matrix_uint_swap_rowcol(). Swap row and column in place. Matrix must be square.
     * @param i index of row
     * @param j index of column
     * @return error code on failure
     */
    int swap_rowcol( size_t const i, size_t const j ){ return gsl_matrix_uint_swap_rowcol( get(), i, j ); }
    /**
     * C++ version of gsl_matrix_uint_transpose().
     * @return error code on failure.
     */
    int transpose(){ return gsl_matrix_uint_transpose( get() ); }
    /**
     * C++ version of gsl_matrix_uint_transpose_memcpy().
     * @param src matrix_uint whose transpose it to be copied to @c this
     * @return error code on failure
     */
    int transpose_memcpy( matrix_uint const& src ){
      return gsl_matrix_uint_transpose_memcpy( get(), src.get() ); }
    /**
     * C++ version of gsl_matrix_uint_max_index().
     * @param imax row index of the first maximum element in the matrix_uint
     * @param jmax column index of the first maximum element in the matrix_uint
     */
    void max_index( size_t* imax, size_t* jmax ) const {
      gsl_matrix_uint_max_index( get(), imax, jmax ); }
    /**
     * C++ version of gsl_matrix_uint_min_index().
     * @param imin row index of the first minimum element in the matrix_uint
     * @param jmin column index of the first minimum element in the matrix_uint
     */
    void min_index( size_t* imin, size_t* jmin ) const {
      gsl_matrix_uint_min_index( get(), imin, jmin ); }
    /**
     * C++ version of gsl_matrix_uint_minmax_index().
     * @param imin row index of the first minimum element in the matrix_uint
     * @param jmin column index of the first minimum element in the matrix_uint
     * @param imax row index of the first maximum element in the matrix_uint
     * @param jmax column index of the first maximum element in the matrix_uint
     */
    void minmax_index( size_t* imin, size_t* jmin, size_t* imax, size_t* jmax ) const {
      gsl_matrix_uint_minmax_index( get(), imin, jmin, imax, jmax ); }
    /**
     * C++ version of gsl_matrix_uint_mul_elements(). Multiply matrices elementwise.
     * @param b Another matrix_uint
     * @return error code on failure
     */
    int
    mul_elements( matrix_uint const& b ){
          return gsl_matrix_uint_mul_elements( get(), b.get() ); }
    /**
     * C++ version of gsl_matrix_uint_div_elements(). Divide each element of @c this by the
     * corrsponding element of @c b
     * @param b Another matrix_uint
     * @return error code on failure
     */
    int div_elements( matrix_uint const& b ){
      return gsl_matrix_uint_div_elements( get(), b.get() ); }
    /**
     * C++ version of gsl_matrix_uint_add_diagonal().
     * @param x A constant
     * @return error code on failure
     */
    int add_diagonal( unsigned int const x ){
      return gsl_matrix_uint_add_diagonal( get(), x ); }
    /**
     * C++ version of gsl_matrix_uint_get_row().
     * @param v A vector_uint
     * @param i The index of the row
     * @return error code on failure
     */
    int get_row( vector_uint& v, size_t const i ) const {
      return gsl_matrix_uint_get_row( v.get(), get(), i ); }
    /**
     * C++ version of gsl_matrix_uint_get_col().
     * @param v A vector_uint
     * @param j The index of the column
     * @return error code on failure
     */
    int get_col( vector_uint& v, size_t const j ) const {
      return gsl_matrix_uint_get_col( v.get(), get(), j ); }
    /**
     * C++ version of gsl_matrix_uint_set_row().
     * @param i The index of the row
     * @param v A vector_uint
     * @return error code on failure
     */
    int set_row( size_t const i, vector_uint const& v ){
      return gsl_matrix_uint_set_row( get(), i, v.get() ); }
    /**
     * C++ version of gsl_matrix_uint_set_col().
     * @param j The index of the column
     * @param v A vector_uint
     * @return error code on failure
     */
    int set_col( size_t const j, vector_uint const& v ){
      return gsl_matrix_uint_set_col( get(), j, v.get() ); }
    // Extra functions for []
    /**
     * This function allows us to use a matrix_uint like an array. Use with caution.
     * Although @c matrix_uint[i][j] is possible, it is much less efficient than
     * matrix_uint::set(). The effect is the same as row()
     * @param i The index of the row
     * @return A vector_uint representing a row
     */
    vector_uint operator[]( size_t const i ){
      // First check that iterator is initialised.
      if( ccgsl_pointer == 0 ){
  	gsl_error( "matrix_uint is null", __FILE__, __LINE__, exception::GSL_EFAILED );
  	return vector_uint();
      }
      gsl_vector_uint* w = static_cast<gsl_vector_uint*>( malloc( sizeof( gsl_vector_uint ) ) );
      *w = gsl_matrix_uint_row( ccgsl_pointer, i ).vector;
      return vector_uint( w );
    }
    /**
     * This function allows us to use a matrix_uint like an array. Use with caution.
     * Although @c matrix_uint[i][j] is possible, it is much less efficient than
     * matrix_uint::set(). The effect is the same as row()
     * @param i The index of the row
     * @return A vector_uint representing a row
     */
    vector_uint const operator[]( size_t const i ) const {
      // First check that iterator is initialised.
      if( ccgsl_pointer == 0 ){
  	gsl_error( "matrix_uint is null", __FILE__, __LINE__, exception::GSL_EFAILED );
  	return vector_uint();
      }
      gsl_vector_uint* w = static_cast<gsl_vector_uint*>( malloc( sizeof( gsl_vector_uint ) ) );
      *w = gsl_matrix_uint_row( ccgsl_pointer, i ).vector;
      return vector_uint( w );
    }
  };

  // Extra functions for vector_uint allocation from matrix_uint objects
  vector_uint vector_uint::alloc_row_from_matrix( matrix_uint& m, size_t const i ){
    return vector_uint ( gsl_vector_uint_alloc_row_from_matrix( m.get(), i ) ); }
   vector_uint vector_uint::alloc_col_from_matrix( matrix_uint& m, size_t const i ){
    return vector_uint ( gsl_vector_uint_alloc_col_from_matrix( m.get(), i ) ); }
}
#endif
