/*
 * Copyright (C) 2010 John D Lamb
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or (at
 * your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

#ifndef CCGSL_VECTOR_CHAR_HPP
#define CCGSL_VECTOR_CHAR_HPP

#include<gsl/gsl_vector_char.h>
#include<new>
#include<iterator>

#include"exception.hpp"
#include"block_char.hpp"

// This file is autogenerated

namespace gsl {
  // declare matrix_char class
  class matrix_char;
  /**
   * This class handles vector_char objects as shared handles. It models a random access container
   * so that STL functions work with vector_char.
   *
   * Note that vector_char_views are implemented as vector_char objects here.
   */
  class vector_char {
  public:
    /**
     * The default constructor is only really useful for assigning to.
     */
    vector_char(){
      ccgsl_pointer = 0;
      // just plausibly we could fail to allocate count
      try { count = new size_t; } catch( std::bad_alloc& e ){
	throw e;
      }
      *count = 1; // initially there is just one reference to ccgsl_pointer
    }
    // Refines random access container
    // Refines assignable
    /**
     * The default constructor creates a new vector_char with n elements
     * @param n The number of elements in the vector_char
     */
    explicit vector_char( size_t const n ){
      ccgsl_pointer = gsl_vector_char_alloc( n );
      // just plausibly we could allocate vector_char but not count
      try { count = new size_t; } catch( std::bad_alloc& e ){
	// try to tidy up before rethrowing
	gsl_vector_char_free( ccgsl_pointer );
	throw e;
      }
      *count = 1; // initially there is just one reference to ccgsl_pointer
    }
    /**
     * Could construct from a gsl_vector_char. This is not usually a good idea. In this case
     * we should not use gsl_vector_char_free() to deallocate the memory.
     * @param v The vector_char
     */
    explicit vector_char( gsl_vector_char* v ){
      ccgsl_pointer = v;
      // just plausibly we could fail to allocate count: no further action needed.
      count = new size_t;
      *count = 1; // initially there is just one reference to ccgsl_pointer
    }
    // copy constructor
    /**
     * The copy constructor. This shares the vector_char. Use clone() if you want a full copy.
     * @param v The vector_char to copy.
     */
    vector_char( vector_char const& v ) : ccgsl_pointer( v.ccgsl_pointer ), count( v.count ){
      ++*count; // vector_char is now shared.
    }
    // assignment operator
    /**
     * The assignment operator. This makes a shared copy.
     * @param v The vector_char to copy
     */
    vector_char& operator=( vector_char const& v ){
      // first, possibly delete anything pointed to by @c this
      if( --*count == 0 ){
	if( ccgsl_pointer != 0 ) gsl_vector_char_free( ccgsl_pointer );
	delete count;
      }
      // Then copy
      ccgsl_pointer = v.ccgsl_pointer;
      count = v.count;
      ++*count; // block_char is now shared.
      return *this;
    }
    // clone()
    /**
     * The clone function. Use this if you want a copy of the block_char that does
     * not share the underlying data.
     * @return a new copy of @c this.
     */
    vector_char clone() const {
      vector_char copy( get()->size );
      // Now copy
      gsl_vector_char_memcpy( copy.get(), get() );
      // return new object
      return copy;
    }
    // destructor
    /**
     * The destructor only deletes the pointers if count reaches zero.
     */
    ~vector_char(){
      if( --*count == 0 ){
	// could have allocated null pointer
	if( ccgsl_pointer != 0 ) gsl_vector_char_free( ccgsl_pointer );
	delete count;
      }
    }
    // Refines equality comparable
    // == operator
    /**
     * Two vector_char objects are identically equal if their elements are identical.
     * @param v The vector_char to be compared with @c this
     * @return @c true or @c false according as @c this and @c v have
     * identical elements or not
     */
    bool operator==( vector_char const& v ) const {
      // trivially equal if gsl_vector_char*s are identical
      if( ccgsl_pointer == v.ccgsl_pointer ) return true;
      // trivially not equal if one is zero: != should be same as xor here
      if( (ccgsl_pointer == 0) != (v.ccgsl_pointer == 0 ) ) return false;
      // trivially not equal if sizes are different
      if( ccgsl_pointer->size != v.ccgsl_pointer->size ) return false;
      // check elementwise for equality
      for( size_t i = 0; i < ccgsl_pointer->size; ++i )
  	if( gsl_vector_char_get( ccgsl_pointer, i ) != gsl_vector_char_get( v.ccgsl_pointer, i ) ) return false; 
      return true;
    }
    // != operator
    /**
     * Two vector_char objects are different equal if their elements are not identical.
     * @param v The vector_char to be compared with @c this
     * @return @c false or @c true according as @c this and @c v have
     * identical elements or not
     */
    bool operator!=( vector_char const& v ) const { return not operator==( v ); }
    // Refines forward container
    // Refines less than comparable
    // operator<
    /**
     * A container needs to define an ordering for sorting. This uses
     * standard lexicographical ordering and so is not useful,
     * for example, for checking, that a vector_char is nonnegative.
     * @param v The vector_char to be compared with @c this
     * @return @c false or @c true according as @c this is less than @c v
     * lexicographically
     */
    bool operator<( vector_char const& v ) const {
      // null vector_char comes first
      if( ccgsl_pointer == 0 ) return v.ccgsl_pointer != 0;
      // if v is null then this > v
      if( v.ccgsl_pointer == 0 ) return false;
      // Now compare elementwise
      size_t const  size = ccgsl_pointer->size;
      size_t const  v_size = v.ccgsl_pointer->size;
      size_t const min = size > v_size ? size : v_size;
      for( size_t i = 0; i < min; ++i ){
	char const t = gsl_vector_char_get( ccgsl_pointer, i );
	char const u =gsl_vector_char_get( v.ccgsl_pointer, i );
	if( t < u ) return true;
	if( u < t ) return false;
      }
      // elements match.
      return size < v_size;
    }
    // operator>
    /**
     * A container needs to define an ordering for sorting. This uses
     * standard lexicographical ordering and so is not useful,
     * for example, for checking, that a vector_char is nonnegative.
     * @param v The vector_char to be compared with @c this
     * @return @c false or @c true according as @c this is greater than @c v
     * lexicographically
     */
    bool operator>( vector_char const& v ) const {
      // null vector_char comes first
      if( ccgsl_pointer == 0 ) return false;
      // if v is null then this > v
      if( v.ccgsl_pointer == 0 ) return true;
      // Now compare elementwise
      size_t const  size = ccgsl_pointer->size;
      size_t const  v_size = v.ccgsl_pointer->size;
      size_t const min = size > v_size ? size : v_size;
      for( size_t i = 0; i < min; ++i ){
	char const t = gsl_vector_char_get( ccgsl_pointer, i );
	char const u =gsl_vector_char_get( v.ccgsl_pointer, i );
	if( t > u ) return true;
	if( u > t ) return false;
      }
      // elements match.
      return size > v_size;
    }
    // operator<=
    /**
     * A container needs to define an ordering for sorting. This uses
     * standard lexicographical ordering and so is not useful,
     * for example, for checking, that a vector_char is nonnegative.
     * @param v The vector_char to be compared with @c this
     * @return @c false or @c true according as @c this is less than
     * or equal to @c v lexicographically
     */
    bool operator<=( vector_char const& v ) const {
      return operator<( v ) or operator==( v );
    }
    // operator>=
    /**
     * A container needs to define an ordering for sorting. This uses
     * standard lexicographical ordering and so is not useful,
     * for example, for checking, that a vector_char is nonnegative.
     * @param v The vector_char to be compared with @c this
     * @return @c false or @c true according as @c this is no 
     * less than @c v lexicographically
     */ 
    bool operator>=( vector_char const& v ) const {
      return operator>( v ) or operator==( v );
    }
    // Refines container
    // type value_type
    /**
     * A container must have a value_type.
     */
    typedef char value_type;
    // type reference
    /**
     * A container must have a reference type.
     */
    typedef  value_type& reference;
    // type const_reference
    /**
     * A container must have a constant reference type.
     */
    typedef  value_type const& const_reference;
    // type pointer
    /**
     * A container must have a pointer type.
     */
    typedef  value_type* pointer;
    // type const_pointer
    /**
     * A container must have a constant pointer type.
     */
    typedef  value_type const* const_pointer;
    // type iterator
  private:
    /**
     * The container must have iterator types. We create a suitable class
     * here.
     */
    template<typename container, typename content,bool reverse_t>
    class iterator_base
      : public std::iterator<std::random_access_iterator_tag,ptrdiff_t,container*,container&> {
      friend class vector_char;
    public:
      // // type iterator_traits<vector_char>::difference_type
      /**
       * An iterator must have a difference_type.
       */
      typedef ptrdiff_t difference_type;
    public:
      // // operator*
      /**
       * Dereference the pointer.
       * @return a reference to content
       */
      reference operator*() const {
  	// Always try to return something
  	static content something = 0;
  	// First check that iterator is initialised.
  	if( v == 0 ){
  	  gsl_error( "iterator not initialised", __FILE__, __LINE__, exception::GSL_EFAILED );
  	  return something;
  	} else if( v->ccgsl_pointer == 0 ){
  	  gsl_error( "vector_char not initialised", __FILE__, __LINE__, exception::GSL_EFAILED );
  	  return something;
  	}
  	// Check that position make sense
  	if( position >= static_cast<difference_type>( v->size() ) ){
  	  gsl_error( "trying to dereference beyond rbegin()", __FILE__, __LINE__, exception::GSL_EFAILED );
  	  return something;
  	}
  	if( position <= -1 ){
  	  gsl_error( "trying to dereference beyond begin()", __FILE__, __LINE__, exception::GSL_EFAILED );
  	  return something;
  	}
  	// position and v are valid: return data
  	return *(v->ccgsl_pointer->data + position * v->ccgsl_pointer->stride);
      }
      // // operator->
      /**
       * Dereference the pointer.
       * @return a pointer to content
       */
      pointer operator->() const {
  	// First check that iterator is initialised.
  	if( v == 0 ){
  	  gsl_error( "iterator not initialised", __FILE__, __LINE__, exception::GSL_EFAILED );
  	  return 0;
  	} else if( v->ccgsl_pointer == 0 ){
  	  gsl_error( "vector_char not initialised", __FILE__, __LINE__, exception::GSL_EFAILED );
  	  return 0;
  	}
  	// Check that position make sense
  	if( position >= static_cast<difference_type>( v->size() ) ){
  	  gsl_error( "trying to dereference end()", __FILE__, __LINE__, exception::GSL_EFAILED );
  	  return 0;
  	}
  	if( position <= -1 ){
  	  gsl_error( "trying to dereference rend()", __FILE__, __LINE__, exception::GSL_EFAILED );
  	  return 0;
  	}
  	// position and v are valid: return data
  	return v->ccgsl_pointer->data + position * v->ccgsl_pointer->stride;
      }
      // // operator[]
      /**
       * Get element at i + n by reference ([] operator).
       * @param n The offset from i
       * @return a reference to content
       */
      reference operator[]( difference_type const n ) const {
  	// Always try to return something
  	static content something = 0;
  	// First check that iterator is initialised.
  	if( v == 0 ){
  	  gsl_error( "iterator not initialised", __FILE__, __LINE__, exception::GSL_EFAILED );
  	  return something;
  	} else if( v->ccgsl_pointer == 0 ){
  	  gsl_error( "vector_char not initialised", __FILE__, __LINE__, exception::GSL_EFAILED );
  	  return something;
  	}
  	// Check that position make sense
  	difference_type const p = reverse_t ? position - n : position + n;
  	if( p >= static_cast<difference_type>( v->size() ) ){
  	  gsl_error( "trying to dereference beyond rbegin()", __FILE__, __LINE__, exception::GSL_EFAILED );
  	  return something;
  	}
  	if( p <= -1 ){
  	  gsl_error( "trying to dereference beyond begin()", __FILE__, __LINE__, exception::GSL_EFAILED );
  	  return something;
  	}
  	// p is a valid position
  	return *(v->ccgsl_pointer->data + p * v->ccgsl_pointer->stride);
      }
      // // operator-: find distance between two iterators
      /**
       * The - operator: find distance between two iterators
       * @param i A second iterator
       * @return (signed) distance between @c this and @c i
       */
      difference_type operator-( iterator_base<container,content,reverse_t> const& i ) const {
  	// Warn if either iterator undefined
  	if( v == 0 or i.v == 0 ){
  	  gsl_error( "iterator not initialised", __FILE__, __LINE__, exception::GSL_EFAILED );
  	  return 0;
  	} else if( v->ccgsl_pointer == 0 or i.v->ccgsl_pointer == 0 ){
  	  gsl_error( "vector_char not initialised", __FILE__, __LINE__, exception::GSL_EFAILED );
  	  return 0;
  	}
  	// Warn if iterators do not point to same vector_char
  	if( v->ccgsl_pointer != i.v->ccgsl_pointer ){
  	  gsl_error( "trying to take difference of iterators for different vector_char objects", __FILE__, __LINE__,
  		     exception::GSL_EFAILED );
  	  return 0;
  	}
  	return reverse_t ? i.position - position : position - i.position;
      }
      // // operator!=
      // // operator<
      /**
       * The == operator.
       * @param i The iterator being compared
       * @return @c true or @c false according as i != *this
       */
      bool operator==( iterator_base<container,content,reverse_t> const& i ) const {
	return this->v == i.v and this->position == i.position;
      }
      /**
       * The != operator.
       * @param i The iterator being compared
       * @return @c true or @c false according as i != *this
       */
      bool operator!=( iterator_base<container,content,reverse_t> const& i ) const {
	return not this->operator==( i );
      }
      /**
       * The < operator is used to compare iterators. This only makes sense
       * if the iterators iterate over the same vector_char and the function calls
       * a GSL error handler and returns @c false if they do not.
       * @param i The iterator being compared
       * @return @c true or @c false according as i < j
       */
      bool operator<( iterator_base<container,content,reverse_t> const& i ) const {
  	// Warn if either iterator undefined
  	if( v == 0 or i.v == 0 ){
  	  gsl_error( "iterator not initialised", __FILE__, __LINE__, exception::GSL_EFAILED );
  	  return false;
  	}
  	// Warn if iterators do not point to same vector_char
  	if( v->ccgsl_pointer != i.v->ccgsl_pointer ){
  	  gsl_error( "trying to take difference of iterators for different vector_char objects", __FILE__, __LINE__,
  		     exception::GSL_EFAILED );
  	  return false;
  	}
  	return reverse_t ? i.position < position : position < i.position;
      }
    protected:
      /**
       * Increment the iterator.
       * @return 0 for success, anything else for failure
       */
      void increment(){
  	// Only makes sense if v points to a vector_char
  	if( v == 0 ){
  	  gsl_error( "iterator not initialised", __FILE__, __LINE__, exception::GSL_EFAILED );
  	  return;
  	} else if( v->ccgsl_pointer == 0 ){
  	  gsl_error( "vector_char not initialised", __FILE__, __LINE__, exception::GSL_EFAILED );
  	  return;
  	}
  	// increment position and check against size
  	if( reverse_t ){ if( position >= 0 ) --position; }
  	else { if( position < static_cast<difference_type>( v->size() ) ) ++position; }
      }
      /**
       * Derement the iterator.
       * @return 0 for success, anything else for failure
       */
      void decrement(){
  	// Only makes sense if v points to a vector_char
  	if( v == 0 ){
  	  gsl_error( "iterator not initialised", __FILE__, __LINE__, exception::GSL_EFAILED );
  	  return;
  	} else if( v->ccgsl_pointer == 0 ){
  	  gsl_error( "vector_char not initialised", __FILE__, __LINE__, exception::GSL_EFAILED );
  	  return;
  	}
  	// decrement position and check against size
  	if( reverse_t ){ if( position < static_cast<difference_type>( v->size() ) ) ++position; }
  	else { if( position >= 0 ) --position; }
      }
      /**
       * Shift iterator n places
       * @param n A difference_type value to be added to position of iterator
       */
      void shift( difference_type const n ){
  	// Warn if iterator undefined
  	if( v == 0 ){
  	  gsl_error( "iterator not initialised", __FILE__, __LINE__, exception::GSL_EFAILED );
  	  return;
  	} else if( v->ccgsl_pointer == 0 ){
  	  gsl_error( "vector_char not initialised", __FILE__, __LINE__, exception::GSL_EFAILED );
  	  return;
  	}
  	position += reverse_t ? -n : n;
      }
      /**
       * The iterator is default constructible.
       */
      iterator_base<container,content,reverse_t>(){ v = 0; }
      /**
       * This constructor allows vector_char to create non-default iterators.
       * @param v The vector_char that creates @c this
       * @param position The initial postion of the iterator
       */
      iterator_base<container,content,reverse_t>( container* v, difference_type position )
  	: v( v ), position( position ){}
      /**
       * Store a pointer to a vector_char we can iterate over: 0 if no vector_char.
       */
      container* v;
      /**
       * Mark position of iterator within vector_char.
       */
      difference_type position;
    };
    // Need to know about const_iterator_t
    template<bool reverse_t> class const_iterator_t;
    /**
     * A class template for the two non-const iterators.
     */
    template<bool reverse_t> class iterator_t : public iterator_base<vector_char,char,reverse_t>{
    public:
      // // Refines output iterator
      // // operator=
      /**
       * We can assign one output iterator from another.
       * @param i The iterator to copy
       */
      iterator_t<reverse_t>& operator=( iterator_t<reverse_t> const& i ){
  	iterator_base<vector_char,char,reverse_t>::v = i.v;
  	iterator_base<vector_char,char,reverse_t>::position = i.position;
  	return *this;
      }
      // // Refines forward iterator
      // // operator++ (both)
      /**
       * The prefix ++ operator.
       * @return @c this
       */
      iterator_t<reverse_t>& operator++(){
  	iterator_base<vector_char,char,reverse_t>::increment();
  	return *this;
      }
      /**
       * The postfix ++ operator.
       * @return @c this
       */
      iterator_t<reverse_t> operator++( int ){
  	// return value
  	iterator_t<reverse_t> result( *this );
  	iterator_base<vector_char,char,reverse_t>::increment();
  	return result;
      }
      // // Refines bidirectional iterator
      // // operator-- (both)
      /**
       * The prefix -- operator.
       * @return @c this
       */
      iterator_t<reverse_t>& operator--(){
  	iterator_base<vector_char,char,reverse_t>::decrement();
  	return *this;
      }
      /**
       * The postfix -- operator.
       * @return @c this;
       */
      iterator_t<reverse_t> operator--( int ){
  	// return value
  	iterator_t<reverse_t> result( *this );
  	iterator_base<vector_char,char,reverse_t>::decrement();
  	return result;
      }
      /**
       * Difference type.
       */
      typedef typename iterator_base<vector_char,char,reverse_t>::difference_type
  	difference_type;
      // // operator+=
      /**
       * The += operator.
       * @param n A difference_type value to be added to position of iterator
       * @return @c this
       */
      iterator_t<reverse_t>& operator+=( difference_type const n ){
  	shift( n );
  	return *this;
      }
      // // operator-=
      /**
       * The -= operator.
       * @param n A difference_type value to be subtracted from position of iterator
       * @return @c this
       */
      iterator_t<reverse_t>& operator-=( difference_type const n ){
  	shift( -n );
  	return *this;
      }
      // // operator+ (n+i)(i+n)
      /**
       * The + operator.
       * @param n A difference_type value to be added
       * @return A new iterator
       * @see ccgsl::operator+();
       */
      iterator_t<reverse_t> operator+( difference_type const n ) const {
  	iterator_t<reverse_t> result( *this );
  	result.shift( n );
  	return result;
      }
      // // operator- (n-i)(i-n)(i-j)
      /**
       * The - operator: subtract distance from iterator
       * @param n A difference_type value to be subtracted
       * @return A new iterator
       * @see ccgsl::operator-();
       */
      iterator_t<reverse_t> operator-( difference_type const n ) const {
  	iterator_t<reverse_t> result( *this );
  	result.shift( -n );
  	return result;
      }
      /**
       * The - operator: find distance between two iterators
       * @param i A second iterator
       * @return (signed) distance between @c this and @c i
       */
      difference_type operator-( iterator_t<reverse_t> const& i ) const {
  	return iterator_base<vector_char,char,reverse_t>::operator-( i );
      }
      /**
       * The - operator: find distance between two iterators
       * @param i A const iterator
       * @return (signed) distance between @c this and @c i
       */
      difference_type operator-( const_iterator_t<reverse_t> const& i ) const {
  	// Warn if either iterator undefined
  	if( this->v == 0 or i.v == 0 ){
  	  gsl_error( "iterator not initialised", __FILE__, __LINE__, exception::GSL_EFAILED );
  	  return 0;
  	} else if( this->v->ccgsl_pointer == 0 or i.v->ccgsl_pointer == 0 ){
  	  gsl_error( "vector_char not initialised", __FILE__, __LINE__, exception::GSL_EFAILED );
  	  return 0;
  	}
  	// Warn if iterators do not point to same vector_char
  	if( this->v->ccgsl_pointer != i.v->ccgsl_pointer ){
  	  gsl_error( "trying to take difference of iterators for different vector_char objects", __FILE__, __LINE__,
  		     exception::GSL_EFAILED );
  	  return 0;
  	}
  	return reverse_t ? i.position - this->position : this->position - i.position;
      }
      /**
       * Comparison with const iterator.
       * @param i another iterator
       * @return @c true or @c false according as @c this points to same element as @c i
       */
      bool operator==( const_iterator_t<reverse_t> const& i ) const {
       	return this->v == i.v and this->position == i.position;
      }
      /**
       * Comparison with const iterator.
       * @param i another iterator
       * @return @c false or @c true according as @c this points to same element as @c i
       */
      bool operator!=( const_iterator_t<reverse_t> const& i ) const {
       	return not this->operator==( i );
      }
      /**
       * Comparison with const iterator.
       * @param i another iterator
       * @return @c true or @c false according as @c this points to earlier element than @c i
       */
      bool operator<( const_iterator_t<reverse_t> const& i ) const {
  	// Warn if either iterator undefined
  	if( this->v == 0 or i.v == 0 ){
  	  gsl_error( "iterator not initialised", __FILE__, __LINE__, exception::GSL_EFAILED );
  	  return false;
  	}
  	// Warn if iterators do not point to same vector_char
  	if( this->v->ccgsl_pointer != i.v->ccgsl_pointer ){
  	  gsl_error( "trying to take difference of iterators for different vector_char objects", __FILE__, __LINE__,
  		     exception::GSL_EFAILED );
  	  return false;
  	}
  	return reverse_t ? i.position < this->position : this->position < i.position;
      }
      /**
       * The default constructor.
       */
      iterator_t<reverse_t>() : iterator_base<vector_char,char,reverse_t>(){}
    protected:
      friend class vector_char;
      // We need a constructor for vector_char
      /**
       * This constructor allows vector_char to create non-default iterators.
       * @param v The vector_char that creates @c this
       * @param position The initial postion of the iterator
       */
      iterator_t<reverse_t>( vector_char* v, difference_type position )
      : iterator_base<vector_char,char,reverse_t>( v, position ){}
    };
    /**
     * A class template for the const iterators.
     */
    template<bool reverse_t> class const_iterator_t
      : public iterator_base<vector_char const,char,reverse_t>{
    public:
      // // Refines output iterator
      // // operator=
      /**
       * We can assign one output iterator from another.
       * @param i The iterator to copy
       */
      const_iterator_t<reverse_t>& operator=( const_iterator_t<reverse_t> const& i ){
  	iterator_base<vector_char const,char,reverse_t>::v = i.v;
  	iterator_base<vector_char const,char,reverse_t>::position = i.position;
  	return *this;
      }
      // // Refines forward iterator
      // // operator++ (both)
      /**
       * The prefix ++ operator.
       * @return @c this
       */
      const_iterator_t<reverse_t>& operator++(){
  	iterator_base<vector_char const,char,reverse_t>::increment();
  	return *this;
      }
      /**
       * The postfix ++ operator.
       * @return @c this
       */
      const_iterator_t<reverse_t> operator++( int ){
  	// return value
  	const_iterator_t<reverse_t> result( *this );
  	iterator_base<vector_char const,char,reverse_t>::increment();
  	return result;
      }
      // // Refines bidirectional iterator
      // // operator-- (both)
      /**
       * The prefix -- operator.
       * @return @c this
       */
      const_iterator_t<reverse_t>& operator--(){
  	iterator_base<vector_char const,char,reverse_t>::decrement();
  	return *this;
      }
      /**
       * The postfix -- operator.
       * @return @c this
       */
      const_iterator_t<reverse_t> operator--( int ){
  	// return value
  	const_iterator_t<reverse_t> result( *this );
  	iterator_base<vector_char const,char,reverse_t>::decrement();
  	return result;
      }
      /**
       * Difference type.
       */
      typedef typename iterator_base<vector_char const,char,reverse_t>::difference_type
  	difference_type;
      // // operator+=
      /**
       * The += operator.
       * @param n A difference_type value to be added to position of iterator
       * @return @c this
       */
      const_iterator_t<reverse_t>& operator+=( difference_type const n ){
  	shift( n );
  	return *this;
      }
      // // operator-=
      /**
       * The -= operator.
       * @param n A difference_type value to be subtracted from position of iterator
       * @return @c this
       */
      const_iterator_t<reverse_t>& operator-=( difference_type const n ){
  	shift( -n );
  	return *this;
      }
      // // operator+ (n+i)(i+n)
      /**
       * The + operator.
       * @param n A difference_type value to be added
       * @return A new iterator
       * @see ccgsl::operator+();
       */
      const_iterator_t<reverse_t> operator+( difference_type const n ) const {
  	const_iterator_t<reverse_t> result( *this );
  	result += n;
  	return result;
      }
      // // operator- (n-i)(i-n)(i-j)
      /**
       * The - operator: subtract distance from iterator
       * @param n A difference_type value to be subtracted
       * @return A new iterator
       * @see ccgsl::operator-();
       */
      const_iterator_t<reverse_t> operator-( difference_type const n ) const {
  	const_iterator_t<reverse_t> result( *this );
  	result -= n;
  	return result;
      }
      /**
       * The - operator: find distance between two iterators
       * @param i A second iterator
       * @return (signed) distance between @c this and @c i
       */
      difference_type operator-( const_iterator_t<reverse_t> const& i ) const {
  	return iterator_base<vector_char const,char,reverse_t>::operator-( i );
      }
      /**
       * The - operator: find distance between two iterators
       * @param i A second iterator
       * @return (signed) distance between @c this and @c i
       */
      difference_type operator-( iterator_t<reverse_t> const& i ) const {
  	// Warn if either iterator undefined
  	if( this->v == 0 or i.v == 0 ){
  	  gsl_error( "iterator not initialised", __FILE__, __LINE__, exception::GSL_EFAILED );
  	  return 0;
  	} else if( this->v->ccgsl_pointer == 0 or i.v->ccgsl_pointer == 0 ){
  	  gsl_error( "vector_char not initialised", __FILE__, __LINE__, exception::GSL_EFAILED );
  	  return 0;
  	}
  	// Warn if iterators do not point to same vector_char
  	if( this->v->ccgsl_pointer != i.v->ccgsl_pointer ){
  	  gsl_error( "trying to take difference of iterators for different vector_char objects", __FILE__, __LINE__,
  		     exception::GSL_EFAILED );
  	  return 0;
  	}
  	return reverse_t ? i.position - this->position : this->position - i.position;
      }
      /**
       * The default constructor.
       */
      const_iterator_t<reverse_t>() : iterator_base<vector_char,char,reverse_t>(){}
      /**
       * A copy constructor
       * @param i The non-const iterator to copy
       */
      const_iterator_t<reverse_t>( iterator_t<reverse_t> const&i ){
  	const_iterator_t<reverse_t>::v = i.v;
  	const_iterator_t<reverse_t>::position = i.position;
      }
      /**
       * Comparison with non-const iterator.
       * @param i another iterator
       * @return @c true or @c false according as @c this points to same element as @c i
       */
      bool operator==( iterator_t<reverse_t> const& i ) const {
       	return this->v == i.v and this->position == i.position;
      }
      /**
       * Comparison with non-const iterator.
       * @param i another iterator
       * @return @c false or @c true according as @c this points to same element as @c i
       */
      bool operator!=( iterator_t<reverse_t> const& i ) const {
       	return not this->operator==( i );
      }
      /**
       * Comparison with non-const iterator.
       * @param i another iterator
       * @return @c true or @c false according as @c this points to earlier element than @c i
       */
      bool operator<( iterator_t<reverse_t> const& i ) const {
  	// Warn if either iterator undefined
  	if( this->v == 0 or i.v == 0 ){
  	  gsl_error( "iterator not initialised", __FILE__, __LINE__, exception::GSL_EFAILED );
  	  return false;
  	}
  	// Warn if iterators do not point to same vector_char
  	if( this->v->ccgsl_pointer != i.v->ccgsl_pointer ){
  	  gsl_error( "trying to take difference of iterators for different vector_char objects", __FILE__, __LINE__,
  		     exception::GSL_EFAILED );
  	  return false;
  	}
  	return reverse_t ? i.position < this->position : this->position < i.position;
      }
    protected:
      // We need a constructor for vector_char
      friend class vector_char;
      /**
       * This constructor allows vector_char to create non-default iterators.
       * @param v The vector_char that creates @c this
       * @param position The initial postion of the iterator
       */
      const_iterator_t<reverse_t>( vector_char const* v, difference_type position )
      : iterator_base<vector_char const,char,reverse_t>( v, position ){}
    };
  public:
    /**
     * The const_iterator type.
     */
    typedef const_iterator_t<false> const_iterator;
    /**
     * The iterator type.
     */
    typedef iterator_t<false> iterator;
    /**
     * The const_reverse_t type.
     */
    typedef const_iterator_t<true> const_reverse_iterator;
    /**
     * The reverse_iterator type.
     */
    typedef iterator_t<true> reverse_iterator;
    // type difference_type
    /**
     * A container must have a difference_type.
     */
    typedef  const_iterator::difference_type difference_type;
    // type size_type
    /**
     * A container must have a size_type.
     */
    typedef  size_t size_type;
    // begin()
    /**
     * Get iterator pointing to first vector_char element.
     * @return iterator pointing to first vector_char element
     */
    iterator begin(){
      return iterator( this, 0 );
    }
    /**
     * Get iterator pointing to first vector_char element.
     * @return iterator pointing to first vector_char element
     */
    const_iterator begin() const {
      return const_iterator( this, 0 );
    }
    // end()
    /**
     * Get iterator pointing beyond last vector_char element.
     * @return iterator pointing beyond last vector_char element
     */
    iterator end(){
      if( ccgsl_pointer == 0 ) return iterator( this, 0 );
      return iterator( this, size() );
    }
    /**
     * Get iterator pointing beyond last vector_char element.
     * @return iterator pointing beyond last vector_char element
     */
    const_iterator end() const {
      if( ccgsl_pointer == 0 ) return const_iterator( this, 0 );
      return const_iterator( this, size() );
    }
    // size()
    /**
     * The size (number of elements) of the vector_char.
     * @return The size of the vector_char
     */
    size_type size() const { return ccgsl_pointer == 0 ? 0 : ccgsl_pointer->size; }
    // max_size()
    /**
     * The max size (number of elements) of the vector_char. Identical to
     * size but required for a container.
     * @return The size of the vector_char
     */
    size_type max_size() const { return ccgsl_pointer == 0 ? 0 : ccgsl_pointer->size; }
    // empty()
    /**
     * Find if the vector_char is empty.
     * @return @c true if has size zero; otherwise @c false
     */
    bool empty() const { return ccgsl_pointer == 0 or ccgsl_pointer->size == 0; }
    // swap() --- should work even if sizes don't match
    /**
     * Swap two vector_char objects. This works even if the vector_char objects have different sizes
     * because it swaps pointers.
     * @param v The vector_char to swap with @c this.
     */
    void swap( vector_char& v ){
      gsl_vector_char* tmp = ccgsl_pointer; ccgsl_pointer = v.ccgsl_pointer; v.ccgsl_pointer = tmp;
      size_t* tmp2 = count; count = v.count; v.count = tmp2;
    }
    // Refines reversible container
    // rbegin()
    /**
     * Get iterator pointing to first vector_char element.
     * @return iterator pointing to first vector_char element
     */
    reverse_iterator rbegin(){
      if( ccgsl_pointer ==0 ) return reverse_iterator( this, 0 );
      return reverse_iterator( this, size() - 1 );
    }
    /**
     * Get iterator pointing to first vector_char element.
     * @return iterator pointing to first vector_char element
     */
    const_reverse_iterator rbegin() const {
      if( ccgsl_pointer ==0 ) return const_reverse_iterator( this, 0 );
      return const_reverse_iterator( this, size() - 1 );
    }
    // rend()
    /**
     * Get iterator pointing beyon last vector_char element.
     * @return iterator pointing beyond last vector_char element
     */
    reverse_iterator rend(){
      return reverse_iterator( this, -1 );
    }
    /**
     * Get iterator pointing beyon last vector_char element.
     * @return iterator pointing beyond last vector_char element
     */
    const_reverse_iterator rend() const {
      return const_reverse_iterator( this, -1 );
    }
    // operator[]
    /**
     * Get element at position @c n by reference ([] operator).
     * @param n The position of the element
     * @return a reference to a char
     */
    char& operator[]( size_t const n ){
      // Always try to return something
      static char something = 0;
      // First check that iterator is initialised.
      if( ccgsl_pointer == 0 ){
  	gsl_error( "vector_char is null", __FILE__, __LINE__, exception::GSL_EFAILED );
  	return something;
      }
      // Check that position make sense
      if( n >= size() ){
  	gsl_error( "trying to read beyond end of vector_char", __FILE__, __LINE__, exception::GSL_EFAILED );
  	return something;
      }
      // n is a valid position
      return *(ccgsl_pointer->data + n * ccgsl_pointer->stride);
    }
    /**
     * Get element at position @c n by reference ([] operator).
     * @param n The position of the element
     * @return a reference to a char
     */
    char const& operator[]( size_t const n ) const {
      // Always try to return something
      static char something = 0;
      // First check that iterator is initialised.
      if( ccgsl_pointer == 0 ){
  	gsl_error( "vector_char is null", __FILE__, __LINE__, exception::GSL_EFAILED );
  	return something;
      }
      // Check that position make sense
      if( n >= size() ){
  	gsl_error( "trying to read beyond end of vector_char", __FILE__, __LINE__, exception::GSL_EFAILED );
  	return something;
      }
      // n is a valid position
      return *(ccgsl_pointer->data + n * ccgsl_pointer->stride);
    }
  private:
    /**
     * The shared pointer
     */
    gsl_vector_char* ccgsl_pointer;
    /**
     * The shared reference count
     */
    size_t* count;
  public:
    // shared reference functions
    /**
     * Get the gsl_vector_char.
     * @return the gsl_vector_char
     */
    gsl_vector_char* get() {
#ifndef GSL_RANGE_CHECK_OFF
      if( ccgsl_pointer == 0 )
  	gsl_error( "Object not initialised", __FILE__, __LINE__, exception::GSL_EFAULT );
#endif
      return ccgsl_pointer; }
    /**
     * Get the gsl_vector_char.
     * @return the gsl_vector_char
     */
    gsl_vector_char const* get() const {
#ifndef GSL_RANGE_CHECK_OFF
      if( ccgsl_pointer == 0 )
  	gsl_error( "Object not initialised", __FILE__, __LINE__, exception::GSL_EFAULT );
#endif
      return ccgsl_pointer; }
    /**
     * Find if @c this is the only object sharing the gsl_vector_char.
     * @return @c true or @c falses according as 
     * this is the only vector_char object sharing the gsl_vector_char
     */
    bool unique() const { return *count == 1; }
    /**
     * Find how many vector_char objects share this pointer.
     * @return the number of vector_char objects that share this pointer
     */
    size_t use_count() const { return *count; }
    /**
     * Allow conversion to bool.
     * @return @c true or @c false according as @c this contains a pointer
     * to a gsl_vector_char
     */
    operator bool() const { return ccgsl_pointer != 0; }

    // GSL functions
    /**
     * C++ version of gsl_vector_char_calloc(). This constructs a vector_char object with entries
     * initialised to zero.
     * @param n The size of the vector_char
     * @return A vector_char initialised to zero
     */
    static vector_char calloc( size_t const n ){ return vector_char( gsl_vector_char_calloc( n ) ); }
    /**
     * C++ version of gsl_vector_char_set_zero().
     */
    void set_zero(){ gsl_vector_char_set_zero( get() ); }
    /**
     * C++ version of gsl_vector_char_set_all().
     * @param x The value to which all elements are set
     */
    void set_all( char x ){ gsl_vector_char_set_all( get(), x ); }
    /**
     * C++ version of gsl_vector_char_set_basis(). Creates a basis vector_char with one nonzero element.
     * @param i The element to be set to 1.
     * @return error code on failure
     */
    int set_basis( size_t i ){ return gsl_vector_char_set_basis( get(), i ); }
    /**
     * C++ version of gsl_vector_char_memcpy().
     * @param src source vector_char
     * @return error code on failure
     */
    int memcpy( vector_char const& src ){ return gsl_vector_char_memcpy( get(), src.get() ); }
    /**
     * C++ version of gsl_vector_char_reverse().
     * @return error code on failure
     */
    int reverse(){ return gsl_vector_char_reverse( get() ); }
    /**
     * C++ version of gsl_vector_char_swap_elements().
     * @param i first element
     * @param j second element
     * @return error code on failure
     */
    int swap_elements( size_t const i, size_t const j ){
      return gsl_vector_char_swap_elements( get(), i, j ); }
    /**
     * C++ version of gsl_vector_char_max().
     * @return maximum element of vector_char
     */
    char max() const { return gsl_vector_char_max( get() ); }
    /**
     * C++ version of gsl_vector_char_min().
     * @return minimum element of vector_char
     */
    char min() const { return gsl_vector_char_min( get() ); }
    /**
     * C++ version of gsl_vector_char_minmax().
     * @param min_out minimum element of vector_char
     * @param max_out maximum element of vector_char
     */
    void minmax( char* min_out, char* max_out ) const {
      gsl_vector_char_minmax( get(), min_out, max_out ); }
    /**
     * C++ version of gsl_vector_char_max_index().
     * @return index of maximum value of vector_char
     */
    size_t max_index() const { return gsl_vector_char_max_index( get() ); }
    /**
     * C++ version of gsl_vector_char_min_index().
     * @return index of minimum value of vector_char
     */
    size_t min_index() const { return gsl_vector_char_min_index( get() ); }
    /**
     * C++ version of gsl_vector_char_minmax_index().
     * @param imin index of minimum value of vector_char
     * @param imax index of maximum value of vector_char
     */
    void minmax_index( size_t* imin, size_t* imax ) const {
      gsl_vector_char_minmax_index( get(), imin, imax ); }
    /**
     * C++ version of gsl_vector_char_add().
     * @param b vector_char to add to @c this
     * @return error code on failure
     */
    int add( vector_char const& b ){ return gsl_vector_char_add( get(), b.get() ); }
    /**
     * C++ version of gsl_vector_char_sub().
     * @param b vector_char to subtract from @c this
     * @return error code on failure
     */
    int sub( vector_char const& b ){ return gsl_vector_char_sub( get(), b.get() ); }
    /**
     * C++ version of gsl_vector_char_mul().
     * @param b vector_char to multiply elementwise with @c this
     * @return error code on failure
     */
    int mul( vector_char const& b ){ return gsl_vector_char_mul( get(), b.get() ); }
    /**
     * C++ version of gsl_vector_char_div().
     * @param b vector_char to dividev @c this by elementwise
     * @return error code on failure
     */
    int div( vector_char const& b ){ return gsl_vector_char_div( get(), b.get() ); }
    /**
     * C++ version of gsl_vector_char_scale().
     * @param x constant to multiply @c this by
     * @return error code on failure
     */
    int scale( char const x ){ return gsl_vector_char_scale( get(), x ); }
    /**
     * C++ version of gsl_vector_char_add_constant().
     * @param x constant to add to each element of @c this
     * @return error code on failure
     */
    int add_constant( char const x ){ return gsl_vector_char_add_constant( get(), x ); }
    /**
     * C++ version of gsl_vector_char_isnull().
     * @return @c +1 or @c 0 according as elements are all zero or not
     */
    int isnull() const { return gsl_vector_char_isnull( get() ); }
    /**
     * C++ version of gsl_vector_char_ispos().
     * @return @c +1 or @c 0 according as elements are all positive or not
     */
    int ispos() const { return gsl_vector_char_ispos( get() ); }
    /**
     * C++ version of gsl_vector_char_isneg().
     * @return @c +1 or @c 0 according as elements are all negative or not
     */
    int isneg() const { return gsl_vector_char_isneg( get() ); }
    /**
     * C++ version of gsl_vector_char_isnonneg().
     * @return @c +1 or @c 0 according as elements are all nonnegative or not
     */
    int isnonneg() const { return gsl_vector_char_isnonneg( get() ); }
    /**
     * C++ version of gsl_vector_char_get().
     * @param i index of element to get
     * @return value of element
     */
    char get( size_t const i ) const { return gsl_vector_char_get( get(), i ); }
    /**
     * C++ version of gsl_vector_char_set().
     * @param i index to set
     * @param x new value for element
     */
    void set( size_t const i, char x ){ gsl_vector_char_set( get(), i, x ); }
    /**
     * C++ version of gsl_vector_char_ptr().
     * @param i index of element to get
     * @return pointer to element
     */
    char* ptr( size_t const i ){ return gsl_vector_char_ptr( get(), i ); }
    /**
     * C++ version of gsl_vector_char_const_ptr().
     * @param i index of element to get
     * @return pointer to element
     */
    char const* const_ptr( size_t const i ) const { return gsl_vector_char_const_ptr( get(), i ); }
    /**
     * C++ version of gsl_vector_char_fread().
     * @param stream A C file stream
     * @return error code on failure
     */
    int fread( FILE* stream ){ return gsl_vector_char_fread( stream, get() ); }
    /**
     * C++ version of gsl_vector_char_fwrite().
     * @param stream A C file stream
     * @return error code on failure
     */
    int fwrite( FILE* stream ) const { return gsl_vector_char_fwrite( stream, get() ); }
    /**
     * C++ version of gsl_vector_char_fscanf().
     * @param stream A C file stream
     * @return error code on failure
     */
    int fscanf( FILE* stream ){ return gsl_vector_char_fscanf( stream, get() ); }
    /**
     * C++ version of gsl_vector_char_fprintf().
     * @param stream A C file stream
     * @param format %d, %e, %f or %g
     * @return error code on failure
     */
    int fprintf( FILE* stream, char const* format ) const {
      return gsl_vector_char_fprintf( stream, get(), format ); }
    /**
     * C++ version of gsl_vector_char_alloc_from_block().
     * @param b The block_char
     * @param offset The offset within the block_char
     * @param n The number of elements
     * @param stride The stride
     */
    vector_char( block_char& b, size_t const offset, size_t const n, size_t const stride ){
      ccgsl_pointer = gsl_vector_char_alloc_from_block( b.get(), offset, n, stride );
      // just plausibly we could allocate vector_char but not count
      try { count = new size_t; } catch( std::bad_alloc& e ){
	// try to tidy up before rethrowing
	gsl_vector_char_free( ccgsl_pointer );
	throw e;
      }
      *count = 1; // initially there is just one reference to ccgsl_pointer
    }
    /**
     * C++ version of gsl_vector_char_alloc_from_vector().
     * @param v The vector_char
     * @param offset The offset
     * @param n The number of elements
     * @param stride The stride
     */
    vector_char( vector_char& v, size_t const offset, size_t const n, size_t const stride ){
      ccgsl_pointer = gsl_vector_char_alloc_from_vector( v.get(), offset, n, stride );
      // just plausibly we could allocate vector_char but not count
      try { count = new size_t; } catch( std::bad_alloc& e ){
	// try to tidy up before rethrowing
	gsl_vector_char_free( ccgsl_pointer );
	throw e;
      }
      *count = 1; // initially there is just one reference to ccgsl_pointer
    }
    /**
     * C++ version of gsl_vector_char_view_array().
     * @param v An array of type char
     * @param n The size of the vector_char
     * @return A vector_char
     */
    static vector_char view_array( char* v, size_t n ){
      gsl_vector_char* w = static_cast<gsl_vector_char*>( malloc( sizeof( gsl_vector_char ) ) );
      *w = gsl_vector_char_view_array( v, n ).vector;
      return vector_char( w );
    }
    /**
     * C++ version of gsl_vector_char_view_array_with_stride().
     * @param base An array of type char
     * @param stride The stride
     * @param n The size of the vector_char
     * @return A vector_char
     */
    static vector_char view_array_with_stride( char* base, size_t stride, size_t n ){
      gsl_vector_char* w = static_cast<gsl_vector_char*>( malloc( sizeof( gsl_vector_char ) ) );
      *w = gsl_vector_char_view_array_with_stride( base, stride, n ).vector;
      return vector_char( w );
    }
    /**
     * C++ version of gsl_vector_char_const_view_array().
     * @param v An array of type char
     * @param n The size of the vector_char
     * @return A vector_char
     */
    static vector_char const const_view_array( char const* v, size_t n ){
      gsl_vector_char* w = static_cast<gsl_vector_char*>( malloc( sizeof( gsl_vector_char ) ) );
      *w = gsl_vector_char_const_view_array( v, n ).vector;
      return vector_char( w );
    }
    /**
     * C++ version of gsl_vector_char_const_view_array_with_stride().
     * @param base An array of type char
     * @param stride The stride
     * @param n The size of the vector_char
     * @return A vector_char
     */
    static vector_char const const_view_array_with_stride( char const* base, size_t stride, size_t n ){
      gsl_vector_char* w = static_cast<gsl_vector_char*>( malloc( sizeof( gsl_vector_char ) ) );
      *w = gsl_vector_char_const_view_array_with_stride( base, stride, n ).vector;
      return vector_char( w );
    }
    /**
     * C++ version of gsl_vector_char_subvector().
     * @param i The offset
     * @param n The size
     * @return A subvector
     */
    vector_char subvector( size_t i, size_t n ){
      gsl_vector_char* w = static_cast<gsl_vector_char*>( malloc( sizeof( gsl_vector_char ) ) );
      *w = gsl_vector_char_subvector( get(), i, n ).vector;
      return vector_char( w );
    }
    /**
     * C++ version of gsl_vector_char_subvector_with_stride().
     * @param i The offset
     * @param stride The stride
     * @param n The size
     * @return A subvector
     */
    vector_char subvector_with_stride( size_t i, size_t stride, size_t n ){
      gsl_vector_char* w = static_cast<gsl_vector_char*>( malloc( sizeof( gsl_vector_char ) ) );
      *w = gsl_vector_char_subvector_with_stride( get(), i, stride, n ).vector;
      return vector_char( w );
    }
    /**
     * C++ version of gsl_vector_char_subvector_with_stride().
     * @param i The offset
     * @param n The size
     * @return A subvector
     */
    vector_char const const_subvector( size_t i, size_t n ) const {
      gsl_vector_char* w = static_cast<gsl_vector_char*>( malloc( sizeof( gsl_vector_char ) ) );
      *w = gsl_vector_char_const_subvector( get(), i, n ).vector;
      return vector_char( w );
    }
    /**
     * C++ version of gsl_vector_char_subvector_with_stride().
     * @param i The offset
     * @param stride The stride
     * @param n The size
     * @return A subvector
     */
    vector_char const const_subvector_with_stride( size_t i, size_t stride, size_t n ) const {
      gsl_vector_char* w = static_cast<gsl_vector_char*>( malloc( sizeof( gsl_vector_char ) ) );
      *w = gsl_vector_char_const_subvector_with_stride( get(), i, stride, n ).vector;
      return vector_char( w );
    }
    // Extra allocators from matrix_char objects. The definition must come after matrix_char.
    /**
     * C++ version of gsl_vector_char_alloc_row_from_matrix().
     * @param m A matrix_char
     * @param i A row
     * @return A vector_char
     */
    static vector_char alloc_row_from_matrix( matrix_char& m, size_t const i );
    /**
     * C++ version of gsl_vector_char_alloc_col_from_matrix().
     * @param m A amtrix
     * @param j A column
     * @return A vector_char
     */
    static vector_char alloc_col_from_matrix( matrix_char& m, size_t const j );
  };

  /**
   * Allows constant to be added to iterator.
   * @param n The constant
   * @param i The iterator
   * @see vector_char::iterator::operator+()
   */
  inline vector_char::iterator operator+
  ( vector_char::iterator::difference_type const n, vector_char::iterator const& i ){ return i + n; }
  
  /**
   * Allows constant to be added to iterator.
   * @param n The constant
   * @param i The iterator
   * @see vector_char::iterator::operator+()
   */
  inline vector_char::const_iterator operator+
  ( vector_char::const_iterator::difference_type const n, vector_char::const_iterator const& i ){ return i + n; }
  
  /**
   * Allows constant to be added to iterator.
   * @param n The constant
   * @param i The iterator
   * @see vector_char::iterator::operator+()
   */
  inline vector_char::reverse_iterator operator+
  ( vector_char::reverse_iterator::difference_type const n, vector_char::reverse_iterator const& i ){
    return i + n; }
  
  /**
   * Allows constant to be added to iterator.
   * @param n The constant
   * @param i The iterator
   * @see vector_char::iterator::operator+()
   */
  inline vector_char::const_reverse_iterator operator+
  ( vector_char::const_reverse_iterator::difference_type const n, vector_char::const_reverse_iterator const& i ){
    return i + n; }
  
}
#endif
